# Generated by Django 2.2 on 2019-05-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(default='', max_length=10)),
                ('name', models.CharField(default='', max_length=50)),
                ('geolocation_type', models.CharField(default='country', max_length=10)),
                ('country_code', models.CharField(default='', max_length=10)),
                ('supports_region', models.BooleanField()),
                ('supports_city', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CountryGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(default='', max_length=50)),
                ('geolocation_type', models.CharField(default='country_group', max_length=30)),
                ('country_codes', models.TextField(null=True)),
                ('is_worldwide', models.BooleanField()),
                ('supports_region', models.BooleanField()),
                ('supports_city', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='GeoMarket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(default='', max_length=50)),
                ('name', models.CharField(default='', max_length=100)),
                ('geolocation_type', models.CharField(default='geo_market', max_length=50)),
                ('country_code', models.CharField(default='', max_length=10)),
                ('supports_region', models.BooleanField()),
                ('supports_city', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(default='', max_length=50)),
                ('name', models.CharField(default='', max_length=100)),
                ('geolocation_type', models.CharField(default='region', max_length=50)),
                ('country_code', models.CharField(default='', max_length=10)),
                ('country_name', models.CharField(default='', max_length=100)),
                ('supports_region', models.BooleanField()),
                ('supports_city', models.BooleanField()),
            ],
        ),
    ]
