# Generated by Django 2.2 on 2019-05-22 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrygroup',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
