# Generated by Django 2.2 on 2019-05-29 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_countrygroup_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectoralDistrict',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(default='', max_length=50)),
                ('name', models.CharField(default='', max_length=255)),
                ('geolocation_type', models.CharField(default='electoral_district', max_length=50)),
                ('country_code', models.CharField(default='US', max_length=10)),
                ('supports_region', models.BooleanField(null=True)),
                ('supports_city', models.BooleanField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='country',
            name='supports_city',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='supports_region',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='countrygroup',
            name='is_worldwide',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='countrygroup',
            name='supports_city',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='countrygroup',
            name='supports_region',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='geomarket',
            name='supports_city',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='geomarket',
            name='supports_region',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='supports_city',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='supports_region',
            field=models.BooleanField(null=True),
        ),
    ]
