# Generated by Django 2.2 on 2019-06-05 13:16

import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('location', '0003_auto_20190530_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrygroup',
            name='country_codes',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
