# Generated by Django 2.2 on 2019-06-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('location', '0004_auto_20190605_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrygroup',
            name='region',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
