apiVersion: v1
kind: Service
metadata:
  name: dev2-filed-potter-facebook-product-catalogs-background-tasks
  labels:
    run: dev2-filed-potter-facebook-product-catalogs-background-tasks
spec:
  ports:
    - port: 46351
  selector:
    run: dev2-filed-potter-facebook-product-catalogs-background-tasks