from GoogleTuring.Api.Catalogs.Views.ViewColumnsMaster.Levels.Breakdowns.Keywords.CampaignKeywordsDimensionColumnsMaster import \
    CampaignKeywordsDimensionColumnsMaster
from GoogleTuring.Api.Catalogs.Views.ViewColumnsMaster.MetricColumnsBase import MetricColumnsBase
from GoogleTuring.Api.Catalogs.Views.ViewColumnsMaster.MetricColumnsMaster import MetricColumnsMaster


class CampaignKeywordsMetricColumnsMaster(MetricColumnsBase):
    AVAILABLE_DIMENSIONS = CampaignKeywordsDimensionColumnsMaster.DIMENSIONS
    METRICS = [
        MetricColumnsMaster.absolute_top_impression_percentage,
        MetricColumnsMaster.active_view_cpm,
        MetricColumnsMaster.active_view_ctr,
        MetricColumnsMaster.active_view_impressions,
        MetricColumnsMaster.active_view_measurability,
        MetricColumnsMaster.active_view_measurable_cost,
        MetricColumnsMaster.active_view_measurable_impressions,
        MetricColumnsMaster.active_view_viewability,
        MetricColumnsMaster.all_conversion_rate,
        MetricColumnsMaster.all_conversions,
        MetricColumnsMaster.all_conversion_value,
        MetricColumnsMaster.average_cost,
        MetricColumnsMaster.average_cpc,
        MetricColumnsMaster.average_cpe,
        MetricColumnsMaster.average_cpm,
        MetricColumnsMaster.average_cpv,
        MetricColumnsMaster.average_pageviews,
        MetricColumnsMaster.average_position,
        MetricColumnsMaster.average_time_on_site,
        MetricColumnsMaster.bounce_rate,
        MetricColumnsMaster.click_assisted_conversions,
        MetricColumnsMaster.click_assisted_conversions_over_last_click_conversions,
        MetricColumnsMaster.click_assisted_conversion_value,
        MetricColumnsMaster.clicks,
        MetricColumnsMaster.conversion_rate,
        MetricColumnsMaster.conversions,
        MetricColumnsMaster.conversion_value,
        MetricColumnsMaster.cost,
        MetricColumnsMaster.cost_per_all_conversion,
        MetricColumnsMaster.cost_per_conversion,
        MetricColumnsMaster.cost_per_current_model_attributed_conversion,
        MetricColumnsMaster.cross_device_conversions,
        MetricColumnsMaster.ctr,
        MetricColumnsMaster.current_model_attributed_conversions,
        MetricColumnsMaster.current_model_attributed_conversion_value,
        MetricColumnsMaster.engagement_rate,
        MetricColumnsMaster.engagements,
        MetricColumnsMaster.gmail_forwards,
        MetricColumnsMaster.gmail_saves,
        MetricColumnsMaster.gmail_secondary_clicks,
        MetricColumnsMaster.historical_creative_quality_score,
        MetricColumnsMaster.historical_landing_page_quality_score,
        MetricColumnsMaster.historical_quality_score,
        MetricColumnsMaster.historical_search_predicted_ctr,
        MetricColumnsMaster.impression_assisted_conversions,
        MetricColumnsMaster.impression_assisted_conversions_over_last_click_conversions,
        MetricColumnsMaster.impression_assisted_conversion_value,
        MetricColumnsMaster.impressions,
        MetricColumnsMaster.interaction_rate,
        MetricColumnsMaster.interactions,
        MetricColumnsMaster.interaction_types,
        MetricColumnsMaster.percent_new_visitors,
        MetricColumnsMaster.search_absolute_top_impression_share,
        MetricColumnsMaster.search_budget_lost_absolute_top_impression_share,
        MetricColumnsMaster.search_budget_lost_top_impression_share,
        MetricColumnsMaster.search_exact_match_impression_share,
        MetricColumnsMaster.search_impression_share,
        MetricColumnsMaster.search_rank_lost_absolute_top_impression_share,
        MetricColumnsMaster.search_rank_lost_impression_share,
        MetricColumnsMaster.search_rank_lost_top_impression_share,
        MetricColumnsMaster.search_top_impression_share,
        MetricColumnsMaster.top_impression_percentage,
        MetricColumnsMaster.value_per_all_conversion,
        MetricColumnsMaster.value_per_conversion,
        MetricColumnsMaster.value_per_current_model_attributed_conversion,
        MetricColumnsMaster.video_quartile_100_rate,
        MetricColumnsMaster.video_quartile_25_rate,
        MetricColumnsMaster.video_quartile_50_rate,
        MetricColumnsMaster.video_quartile_75_rate,
        MetricColumnsMaster.video_view_rate,
        MetricColumnsMaster.video_views,
        MetricColumnsMaster.view_through_conversions,
    ]
