# Generated by Django 2.2 on 2019-05-06 22:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticAdPreview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('preview', models.CharField(blank=True, max_length=10000)),
                ('facebook_preview_type', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
