import numpy as np

from Core.Dexter.Infrastructure.Domain.FuzzyEngine.FuzzySets.FuzzyMembershipFunction import LinearMembershipFunction
from Core.Dexter.Infrastructure.Domain.FuzzyEngine.FuzzySets.FuzzySets import LinguisticVariable, Fuzzyfier
from FacebookDexter.Engine.Algorithms.FuzzyRuleBasedOptimization.Metrics.FacebookAvailableMetricEnum import \
    FacebookAvailableMetricEnum
from FacebookDexter.Infrastructure.Domain.FuzzyEngine.FacebookFuzzySets import FacebookLinguisticVariableEnum

INCREASING_LINEAR_PARAMS = {
    "a": 2.0 / np.pi,
    "b": 0.0
}

DECREASING_LINEAR_PARAMS = {
    "a": -2.0 / np.pi,
    "b": 0.0
}

INCREASING_LINEAR_PARAMS_CPM = {
    "a": 16 / (7 * np.pi),
    "b": -(1 / 7)
}

DECREASING_LINEAR_PARAMS_CPM = {
    "a": -16 / (7 * np.pi),
    "b": -(1 / 7)
}

TREND_METRIC_FUZZYFIER_COLLECTION = [
    Fuzzyfier(metric_name=FacebookAvailableMetricEnum.CPC.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=FacebookAvailableMetricEnum.CPM.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=FacebookAvailableMetricEnum.CTR.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=FacebookAvailableMetricEnum.COST_PER_RESULT.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=FacebookAvailableMetricEnum.COST_PER_APP_INSTALL.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=FacebookAvailableMetricEnum.COST_PER_PURCHASE.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=FacebookAvailableMetricEnum.COST_PER_THRUPLAY.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=FacebookAvailableMetricEnum.CR.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=FacebookAvailableMetricEnum.ENGAGEMENT_RATE.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=FacebookAvailableMetricEnum.ROAS.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=FacebookAvailableMetricEnum.RESULTS.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=FacebookAvailableMetricEnum.SPEND.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=FacebookAvailableMetricEnum.REACH.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=FacebookAvailableMetricEnum.LINK_CLICKS.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=FacebookAvailableMetricEnum.PAGE_LIKES.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=FacebookAvailableMetricEnum.IMPRESSIONS.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=FacebookAvailableMetricEnum.PURCHASES.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=FacebookAvailableMetricEnum.VIDEO_PLAYS.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=FacebookAvailableMetricEnum.LEADS.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=FacebookAvailableMetricEnum.RSVPS.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=FacebookAvailableMetricEnum.APP_INSTALLS.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=FacebookAvailableMetricEnum.CONVERSIONS.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=FacebookAvailableMetricEnum.THRUPLAYS.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=FacebookAvailableMetricEnum.UNIQUE_CLICKS.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=FacebookAvailableMetricEnum.POST_LIKES.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=FacebookAvailableMetricEnum.POST_COMMENTS.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=FacebookAvailableMetricEnum.POST_SHARES.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=FacebookAvailableMetricEnum.POST_VIEWS.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=FacebookAvailableMetricEnum.PURCHASES_VALUE.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=FacebookAvailableMetricEnum.CLICKS.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))])
]
