apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev2-filed-potter-facebook-accounts-api
spec:
  selector:
    matchLabels:
      run: dev2-filed-potter-facebook-accounts-api
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1       
      maxUnavailable: 0
  template:
    metadata:
      labels:
        run: dev2-filed-potter-facebook-accounts-api
    spec:
      imagePullSecrets:
      - name: regcred        
      containers:
      - name: dev2-filed-potter-facebook-accounts-api
        image: ct.filed.com/dev2-filed-potter-facebook-accounts-api:v0.1
        imagePullPolicy: Always
      #  livenessProbe:
      #    httpGet:
      #      path: /api/v1/facebook-accounts/version
      #      port: 47200
      #    initialDelaySeconds: 5
      #    periodSeconds: 5  
        ports: 
        - containerPort : 47200
      #   volumeMounts:
      #   - name: persistent-storage
      #     mountPath: /app/Filed.Users.API/logs
      # volumes:
      # - name: persistent-storage
      #   persistentVolumeClaim:
      #     claimName: mss-logs-claim