RULES_CAMPAIGN_CREATE_AUDIENCE = [
    # RuleBase(rtype=RuleTypeEnum.AUDIENCE,
    #          channel=ChannelEnum.FACEBOOK,
    #          category=RuleCategoryEnum.IMPROVE_CPR,
    #          importance=RuleImportanceEnum.HIGH,
    #          source=RuleSourceEnum.DEXTER,
    #          level=LevelEnum.CAMPAIGN,
    #          action=ActionEnum.NONE,
    #          redirect=RuleRedirectEnum.CREATE_RETARGETING_AUDIENCE,
    #          template="Dexter noticed your <id=1&metric_name=COST_PER_RESULT&metric_type=1&antecedent_type=7> has increased by <id=1&value=null> in the last "
    #                   "<id=1&time_interval=14> days. You should create a retargeting audience and give your campaign a boost.",
    #          breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE,
    #                                               action_breakdown=ActionBreakdownEnum.NONE),
    #          time_interval=DaysEnum.THREE_MONTHS,
    #          connective=Connective(LogicOperatorEnum.AND),
    #          antecedents=[
    #              Antecedent(aid=1,
    #                         atype=AntecedentTypeEnum.FUZZY_TREND,
    #                         metric=AvailableMetricEnum.COST_PER_RESULT.value,
    #                         operator=LogicOperatorEnum.EQUALS,
    #                         expected_value=LinguisticVariableEnum.INCREASING),
    #              Antecedent(aid=2,
    #                         atype=AntecedentTypeEnum.VALUE,
    #                         metric=AvailableMetricEnum.PROSPECTING_CAMPAIGN.value,
    #                         operator=LogicOperatorEnum.EQUALS,
    #                         expected_value=True)
    #          ]),
    # RuleBase(rtype=RuleTypeEnum.AUDIENCE,
    #          channel=ChannelEnum.FACEBOOK,
    #          category=RuleCategoryEnum.IMPROVE_CPR,
    #          importance=RuleImportanceEnum.HIGH,
    #          source=RuleSourceEnum.DEXTER,
    #          level=LevelEnum.CAMPAIGN,
    #          action=ActionEnum.NONE,
    #          redirect=RuleRedirectEnum.CREATE_RETARGETING_AUDIENCE,
    #          template="Dexter noticed your <id=1&metric_name=ROAS&metric_type=1&antecedent_type=7> has decreased by <id=1&value=null> in the last "
    #                   "<id=1&time_interval=14> days. You should create a retargeting audience and give your campaign a boost.",
    #          breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE,
    #                                               action_breakdown=ActionBreakdownEnum.NONE),
    #          time_interval=DaysEnum.THREE_MONTHS,
    #          connective=Connective(LogicOperatorEnum.AND),
    #          antecedents=[
    #              Antecedent(aid=1,
    #                         atype=AntecedentTypeEnum.FUZZY_TREND,
    #                         metric=AvailableMetricEnum.ROAS.value,
    #                         operator=LogicOperatorEnum.EQUALS,
    #                         expected_value=LinguisticVariableEnum.DECREASING),
    #              Antecedent(aid=2,
    #                         atype=AntecedentTypeEnum.VALUE,
    #                         metric=AvailableMetricEnum.PROSPECTING_CAMPAIGN.value,
    #                         operator=LogicOperatorEnum.EQUALS,
    #                         expected_value=True)
    #          ]),
]
