RULES_AD_GENERAL = [
    # RuleBase(rtype=RuleTypeEnum.BUDGET_AND_BID,
    #          channel=ChannelEnum.FACEBOOK,
    #          category=RuleCategoryEnum.IMPROVE_CPR,
    #          importance=RuleImportanceEnum.HIGH,
    #          source=RuleSourceEnum.DEXTER,
    #          level=LevelEnum.AD,
    #          action=ActionEnum.NONE,
    #          redirect=RuleRedirectEnum.EDIT_STRUCTURE,
    #          template="Your reach has decreased, but why? Your ads quality is also low,  at this point your ads are being penalized and delivery "
    #                   "is being affected. Dexter suggests creating new ads with new targeting.",
    #          breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE,
    #                                               action_breakdown=ActionBreakdownEnum.NONE),
    #          time_interval=DaysEnum.THREE_MONTHS,
    #          connective=Connective(LogicOperatorEnum.AND),
    #          antecedents=[
    #              Antecedent(aid=1,
    #                         atype=AntecedentTypeEnum.VALUE,
    #                         metric=AvailableMetricEnum.OBJECTIVE.value,
    #                         operator=LogicOperatorEnum.EQUALS,
    #                         expected_value=ObjectiveEnum.REACH),
    #              Antecedent(aid=2,
    #                         atype=AntecedentTypeEnum.FUZZY_VALUE,
    #                         metric=AvailableMetricEnum.REACH.value,
    #                         operator=LogicOperatorEnum.EQUALS,
    #                         expected_value=LinguisticVariableEnum.DECREASING),
    #              Antecedent(aid=3,
    #                         atype=AntecedentTypeEnum.VALUE,
    #                         metric=AvailableMetricEnum.QUALITY_RANKING.value,
    #                         operator=LogicOperatorEnum.IN,
    #                         expected_value=LOW_QUALITY_RANKING)
    #          ]),
]
