RULES_CAMPAIGN_GENERAL = [
    # app installs
    # RuleBase(rtype=RuleTypeEnum.CREATIVE,
    #          channel=ChannelEnum.FACEBOOK,
    #          category=RuleCategoryEnum.IMPROVE_CPR,
    #          importance=RuleImportanceEnum.HIGH,
    #          source=RuleSourceEnum.DEXTER,
    #          level=LevelEnum.CAMPAIGN,
    #          action=ActionEnum.NONE,
    #          redirect=RuleRedirectEnum.EDIT_STRUCTURE,
    #          template="Your app install <id=1&metric_name=RESULTS&metric_type=1&antecedent_type=8>"
    #                   "are decreasing in the last <id=1&time_interval=7>. Dexter recommends AB testing new ad copy or "
    #                   "new creatives to drive a better results with your app installs.",
    #          breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE,
    #                                               action_breakdown=ActionBreakdownEnum.NONE),
    #          time_interval=DaysEnum.THREE_MONTHS,
    #          connective=Connective(LogicOperatorEnum.AND),
    #          antecedents=[
    #              Antecedent(aid=1,
    #                         atype=AntecedentTypeEnum.VALUE,
    #                         metric=AvailableMetricEnum.OBJECTIVE.value,
    #                         operator=LogicOperatorEnum.EQUALS,
    #                         expected_value=ObjectiveEnum.APP_INSTALLS.value),
    #              Antecedent(aid=2,
    #                         atype=AntecedentTypeEnum.FUZZY_TREND,
    #                         metric=AvailableMetricEnum.RESULTS.value,
    #                         operator=LogicOperatorEnum.EQUALS,
    #                         expected_value=LinguisticVariableEnum.DECREASING)
    #          ]),
    # RuleBase(rtype=RuleTypeEnum.CREATIVE,
    #          channel=ChannelEnum.FACEBOOK,
    #          category=RuleCategoryEnum.IMPROVE_CPC,
    #          importance=RuleImportanceEnum.HIGH,
    #          source=RuleSourceEnum.DEXTER,
    #          level=LevelEnum.CAMPAIGN,
    #          action=ActionEnum.NONE,
    #          redirect=RuleRedirectEnum.EDIT_STRUCTURE,
    #          template="Your <id=1&metric_name=APP_INSTALLS&metric_type=1&antecedent_type=8> has increased by <id=1&value=null>%"
    #                   "in the last <id=1&time_interval=7> days. Dexter recommends "
    #                   "combining your best performing ad copy and creatives to decrease your cost per install.",
    #          breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE,
    #                                               action_breakdown=ActionBreakdownEnum.NONE),
    #          time_interval=DaysEnum.THREE_MONTHS,
    #          connective=Connective(LogicOperatorEnum.AND),
    #          antecedents=[
    #              Antecedent(aid=1,
    #                         atype=AntecedentTypeEnum.VALUE,
    #                         metric=AvailableMetricEnum.OBJECTIVE.value,
    #                         operator=LogicOperatorEnum.EQUALS,
    #                         expected_value=ObjectiveEnum.APP_INSTALLS.value),
    #              Antecedent(aid=2,
    #                         atype=AntecedentTypeEnum.FUZZY_TREND,
    #                         metric=AvailableMetricEnum.COST_PER_APP_INSTALL.value,
    #                         operator=LogicOperatorEnum.EQUALS,
    #                         expected_value=LinguisticVariableEnum.INCREASING)
    #          ]),
    # RuleBase(rtype=RuleTypeEnum.CREATIVE,
    #          channel=ChannelEnum.FACEBOOK,
    #          category=RuleCategoryEnum.IMPROVE_CPC,
    #          importance=RuleImportanceEnum.LOW,
    #          source=RuleSourceEnum.DEXTER,
    #          level=LevelEnum.CAMPAIGN,
    #          action=ActionEnum.NONE,
    #          redirect=RuleRedirectEnum.EDIT_STRUCTURE,
    #          template="Your ad frequency on your campaign is near or above 3.0, which is when ads start to lose their effectiveness. Dexter "
    #                   "suggests launching new ad creatives to help bring the score back down.",
    #          breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE,
    #                                               action_breakdown=ActionBreakdownEnum.NONE),
    #          time_interval=DaysEnum.THREE_MONTHS,
    #          connective=Connective(LogicOperatorEnum.AND),
    #          antecedents=[
    #              Antecedent(aid=1,
    #                         atype=AntecedentTypeEnum.VALUE,
    #                         metric=AvailableMetricEnum.OBJECTIVE.value,
    #                         operator=LogicOperatorEnum.EQUALS,
    #                         expected_value=ObjectiveEnum.APP_INSTALLS.value),
    #              Antecedent(aid=2,
    #                         atype=AntecedentTypeEnum.FUZZY_VALUE,
    #                         metric=AvailableMetricEnum.FREQUENCY.value,
    #                         operator=LogicOperatorEnum.EQUALS,
    #                         expected_value=LinguisticVariableEnum.HIGH)
    #          ]),
    #
    # # brand awareness
    # RuleBase(rtype=RuleTypeEnum.BUDGET_AND_BID,
    #          channel=ChannelEnum.FACEBOOK,
    #          category=RuleCategoryEnum.OPTIMIZE_BUDGET,
    #          importance=RuleImportanceEnum.HIGH,
    #          source=RuleSourceEnum.DEXTER,
    #          level=LevelEnum.CAMPAIGN,
    #          action=ActionEnum.NONE,
    #          redirect=RuleRedirectEnum.EDIT_STRUCTURE,
    #          template="You’re reaching tons of new people each day, <id=1&metric_name=REACH&metric_type=1&antecedent_type=1>"
    #                   " <id=1&value=null> people in the last <id=1&time_interval=7> to be "
    #                   "exact. Your cost per click is relatively stable, too. Dexter suggests increasing your budget by 25%.",
    #          breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE,
    #                                               action_breakdown=ActionBreakdownEnum.NONE),
    #          time_interval=DaysEnum.THREE_MONTHS,
    #          connective=Connective(LogicOperatorEnum.AND),
    #          antecedents=[
    #              Antecedent(aid=1,
    #                         atype=AntecedentTypeEnum.VALUE,
    #                         metric=AvailableMetricEnum.OBJECTIVE.value,
    #                         operator=LogicOperatorEnum.EQUALS,
    #                         expected_value=ObjectiveEnum.BRAND_AWARENESS.value),
    #              Antecedent(aid=2,
    #                         atype=AntecedentTypeEnum.FUZZY_TREND,
    #                         metric=AvailableMetricEnum.REACH.value,
    #                         operator=LogicOperatorEnum.EQUALS,
    #                         expected_value=LinguisticVariableEnum.INCREASING)
    #          ]),
    # RuleBase(rtype=RuleTypeEnum.PERFORMANCE,
    #          channel=ChannelEnum.FACEBOOK,
    #          category=RuleCategoryEnum.IMPROVE_ENGAGEMENT,
    #          importance=RuleImportanceEnum.LOW,
    #          source=RuleSourceEnum.DEXTER,
    #          level=LevelEnum.CAMPAIGN,
    #          action=ActionEnum.NONE,
    #          redirect=RuleRedirectEnum.CAMPAIGN_MANAGER,
    #          template="Your campaign isn’t receiving much engagement. More engagement on brand awareness campaigns helps deliver ads for a reduced cost, "
    #                   "so Dexter suggests asking a question in the first part of the adcopy to create more engagement.",
    #          breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE,
    #                                               action_breakdown=ActionBreakdownEnum.NONE),
    #          time_interval=DaysEnum.THREE_MONTHS,
    #          connective=Connective(LogicOperatorEnum.AND),
    #          antecedents=[
    #              Antecedent(aid=1,
    #                         atype=AntecedentTypeEnum.VALUE,
    #                         metric=AvailableMetricEnum.OBJECTIVE.value,
    #                         operator=LogicOperatorEnum.EQUALS,
    #                         expected_value=ObjectiveEnum.BRAND_AWARENESS.value),
    #              Antecedent(aid=2,
    #                         atype=AntecedentTypeEnum.FUZZY_TREND,
    #                         metric=AvailableMetricEnum.ENGAGEMENT_RATE.value,
    #                         operator=LogicOperatorEnum.EQUALS,
    #                         expected_value=LinguisticVariableEnum.DECREASING)
    #          ]),
    #
    # # conversions
    # RuleBase(rtype=RuleTypeEnum.CREATIVE,
    #          channel=ChannelEnum.FACEBOOK,
    #          category=RuleCategoryEnum.IMPROVE_CPR,
    #          importance=RuleImportanceEnum.HIGH,
    #          source=RuleSourceEnum.DEXTER,
    #          level=LevelEnum.CAMPAIGN,
    #          action=ActionEnum.NONE,
    #          redirect=RuleRedirectEnum.CAMPAIGN_MANAGER,
    #          template="Your <id=1&metric_name=COST_PER_RESULT&metric_type=1&antecedent_type=8> has increased by  <id=1&value=null>% in last "
    #                   "<id=1&time_interval=7> days. Have you tried targeting a more specific audience and excluding audiences you "
    #                   "know won't work or who have converted already?",
    #          breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE,
    #                                               action_breakdown=ActionBreakdownEnum.NONE),
    #          time_interval=DaysEnum.THREE_MONTHS,
    #          connective=Connective(LogicOperatorEnum.AND),
    #          antecedents=[
    #              Antecedent(aid=1,
    #                         atype=AntecedentTypeEnum.VALUE,
    #                         metric=AvailableMetricEnum.OBJECTIVE.value,
    #                         operator=LogicOperatorEnum.EQUALS,
    #                         expected_value=ObjectiveEnum.CONVERSIONS.value),
    #              Antecedent(aid=2,
    #                         atype=AntecedentTypeEnum.FUZZY_TREND,
    #                         metric=AvailableMetricEnum.COST_PER_RESULT.value,
    #                         operator=LogicOperatorEnum.EQUALS,
    #                         expected_value=LinguisticVariableEnum.INCREASING)
    #          ]),
    # RuleBase(rtype=RuleTypeEnum.PERFORMANCE,
    #          channel=ChannelEnum.FACEBOOK,
    #          category=RuleCategoryEnum.IMPROVE_ROAS,
    #          importance=RuleImportanceEnum.MEDIUM,
    #          source=RuleSourceEnum.DEXTER,
    #          level=LevelEnum.CAMPAIGN,
    #          action=ActionEnum.NONE,
    #          redirect=RuleRedirectEnum.CAMPAIGN_MANAGER,
    #          template="Your <id=1&metric_name=ROAS&metric_type=1&antecedent_type=6> has decreased to "
    #                   "<id=1&value=null>% in the last <id=1&time_interval=7> days. "
    #                   "We suggest you consider using lookalike audiences or custom audiences to increase your score. ",
    #          breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE,
    #                                               action_breakdown=ActionBreakdownEnum.NONE),
    #          time_interval=DaysEnum.THREE_MONTHS,
    #          connective=Connective(LogicOperatorEnum.AND),
    #          antecedents=[
    #              Antecedent(aid=1,
    #                         atype=AntecedentTypeEnum.VALUE,
    #                         metric=AvailableMetricEnum.OBJECTIVE.value,
    #                         operator=LogicOperatorEnum.EQUALS,
    #                         expected_value=ObjectiveEnum.CONVERSIONS.value),
    #              Antecedent(aid=2,
    #                         atype=AntecedentTypeEnum.FUZZY_TREND,
    #                         metric=AvailableMetricEnum.ROAS.value,
    #                         operator=LogicOperatorEnum.EQUALS,
    #                         expected_value=LinguisticVariableEnum.DECREASING)
    #          ]),
    # RuleBase(rtype=RuleTypeEnum.CREATIVE,
    #          channel=ChannelEnum.FACEBOOK,
    #          category=RuleCategoryEnum.IMPROVE_CONVERSION_RATE,
    #          importance=RuleImportanceEnum.LOW,
    #          source=RuleSourceEnum.DEXTER,
    #          level=LevelEnum.CAMPAIGN,
    #          action=ActionEnum.NONE,
    #          redirect=RuleRedirectEnum.CAMPAIGN_MANAGER,
    #          template="Your <id=1&metric_name=CR&metric_type=1&antecedent_type=8> has fallen by <id=1&value=null>% over the last <id=1&time_interval=7> days. "
    #                   "Dexter knows video is king right now is proven to help with results. Have you tried uploading a video? Try it now!",
    #          breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE,
    #                                               action_breakdown=ActionBreakdownEnum.NONE),
    #          time_interval=DaysEnum.THREE_MONTHS,
    #          connective=Connective(LogicOperatorEnum.AND),
    #          antecedents=[
    #              Antecedent(aid=1,
    #                         atype=AntecedentTypeEnum.VALUE,
    #                         metric=AvailableMetricEnum.OBJECTIVE.value,
    #                         operator=LogicOperatorEnum.EQUALS,
    #                         expected_value=ObjectiveEnum.CONVERSIONS.value),
    #              Antecedent(aid=2,
    #                         atype=AntecedentTypeEnum.FUZZY_TREND,
    #                         metric=AvailableMetricEnum.CR.value,
    #                         operator=LogicOperatorEnum.EQUALS,
    #                         expected_value=LinguisticVariableEnum.DECREASING)
    #          ]),
    #
    # # lead generation
    # RuleBase(rtype=RuleTypeEnum.PERFORMANCE,
    #          channel=ChannelEnum.FACEBOOK,
    #          category=RuleCategoryEnum.IMPROVE_CPR,
    #          importance=RuleImportanceEnum.HIGH,
    #          source=RuleSourceEnum.DEXTER,
    #          level=LevelEnum.CAMPAIGN,
    #          action=ActionEnum.NONE,
    #          redirect=RuleRedirectEnum.CREATE_LOOKALIKE_AUDIENCE,
    #          template="Your <id=1&metric_name=COST_PER_RESULT&metric_type=1&antecedent_type=8> has decreased by "
    #                   "<id=1&value=null>% in the last <id=1&time_interval=7> days. "
    #                   "Dexter suggests creating lookalikes from your most engaged customer base.",
    #          breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE,
    #                                               action_breakdown=ActionBreakdownEnum.NONE),
    #          time_interval=DaysEnum.THREE_MONTHS,
    #          connective=Connective(LogicOperatorEnum.AND),
    #          antecedents=[
    #              Antecedent(aid=1,
    #                         atype=AntecedentTypeEnum.VALUE,
    #                         metric=AvailableMetricEnum.OBJECTIVE.value,
    #                         operator=LogicOperatorEnum.EQUALS,
    #                         expected_value=ObjectiveEnum.LEAD_GENERATION.value),
    #              Antecedent(aid=2,
    #                         atype=AntecedentTypeEnum.FUZZY_TREND,
    #                         metric=AvailableMetricEnum.COST_PER_RESULT.value,
    #                         operator=LogicOperatorEnum.EQUALS,
    #                         expected_value=LinguisticVariableEnum.DECREASING)
    #          ]),
    # RuleBase(rtype=RuleTypeEnum.CREATIVE,
    #          channel=ChannelEnum.FACEBOOK,
    #          category=RuleCategoryEnum.IMPROVE_CTR,
    #          importance=RuleImportanceEnum.MEDIUM,
    #          source=RuleSourceEnum.DEXTER,
    #          level=LevelEnum.CAMPAIGN,
    #          action=ActionEnum.NONE,
    #          redirect=RuleRedirectEnum.EDIT_STRUCTURE,
    #          template="We've noticed your <id=1&metric_name=CTR&metric_type=1&antecedent_type=8> decreasing over "
    #                   "<id=1&time_interval=7> days which is a sign of ad fatigue. "
    #                   "Dexter suggests launching new ad creatives to help with this. Adding new creatives will give a boost to an existing campaign.",
    #          breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE,
    #                                               action_breakdown=ActionBreakdownEnum.NONE),
    #          time_interval=DaysEnum.THREE_MONTHS,
    #          connective=Connective(LogicOperatorEnum.AND),
    #          antecedents=[
    #              Antecedent(aid=1,
    #                         atype=AntecedentTypeEnum.VALUE,
    #                         metric=AvailableMetricEnum.OBJECTIVE.value,
    #                         operator=LogicOperatorEnum.EQUALS,
    #                         expected_value=ObjectiveEnum.LEAD_GENERATION.value),
    #              Antecedent(aid=2,
    #                         atype=AntecedentTypeEnum.FUZZY_TREND,
    #                         metric=AvailableMetricEnum.CTR.value,
    #                         operator=LogicOperatorEnum.EQUALS,
    #                         expected_value=LinguisticVariableEnum.DECREASING)
    #          ]),
    # RuleBase(rtype=RuleTypeEnum.CREATIVE,
    #          channel=ChannelEnum.FACEBOOK,
    #          category=RuleCategoryEnum.IMPROVE_CONVERSION_RATE,
    #          importance=RuleImportanceEnum.LOW,
    #          source=RuleSourceEnum.DEXTER,
    #          level=LevelEnum.CAMPAIGN,
    #          action=ActionEnum.NONE,
    #          redirect=RuleRedirectEnum.CAMPAIGN_MANAGER,
    #          template="Dexter doesn’t like <id=1&metric_name=CR&metric_type=1&antecedent_type=8> rates dropping by <id=1&value=null>% "
    #                   "in the last <id=1&time_interval=7> days. Usually CR drops are from ad fatigue, or it can be bad targeting. Refresh your ad creatives "
    #                   "as a first step to give them a boost.",
    #          breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE,
    #                                               action_breakdown=ActionBreakdownEnum.NONE),
    #          time_interval=DaysEnum.THREE_MONTHS,
    #          connective=Connective(LogicOperatorEnum.AND),
    #          antecedents=[
    #              Antecedent(aid=1,
    #                         atype=AntecedentTypeEnum.VALUE,
    #                         metric=AvailableMetricEnum.OBJECTIVE.value,
    #                         operator=LogicOperatorEnum.EQUALS,
    #                         expected_value=ObjectiveEnum.LEAD_GENERATION.value),
    #              Antecedent(aid=2,
    #                         atype=AntecedentTypeEnum.FUZZY_TREND,
    #                         metric=AvailableMetricEnum.CR.value,
    #                         operator=LogicOperatorEnum.EQUALS,
    #                         expected_value=LinguisticVariableEnum.DECREASING)
    #          ]),
    #
    # # link clicks
    # RuleBase(rtype=RuleTypeEnum.CREATIVE,
    #          channel=ChannelEnum.FACEBOOK,
    #          category=RuleCategoryEnum.IMPROVE_CPC,
    #          importance=RuleImportanceEnum.HIGH,
    #          source=RuleSourceEnum.DEXTER,
    #          level=LevelEnum.CAMPAIGN,
    #          action=ActionEnum.NONE,
    #          redirect=RuleRedirectEnum.EDIT_STRUCTURE,
    #          template="Dexter noticed your <id=1&metric_name=LINK_CLICKS&metric_type=1&antecedent_type=7> have fallen "
    #                   "<id=1&value=null> over the last <id=1&time_interval=7> days. "
    #                   "Have you considered testing different variations of ad copy or creative?",
    #          breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE,
    #                                               action_breakdown=ActionBreakdownEnum.NONE),
    #          time_interval=DaysEnum.THREE_MONTHS,
    #          connective=Connective(LogicOperatorEnum.AND),
    #          antecedents=[
    #              Antecedent(aid=1,
    #                         atype=AntecedentTypeEnum.VALUE,
    #                         metric=AvailableMetricEnum.OBJECTIVE.value,
    #                         operator=LogicOperatorEnum.EQUALS,
    #                         expected_value=ObjectiveEnum.LINK_CLICKS.value),
    #              Antecedent(aid=2,
    #                         atype=AntecedentTypeEnum.FUZZY_TREND,
    #                         metric=AvailableMetricEnum.LINK_CLICKS.value,
    #                         operator=LogicOperatorEnum.EQUALS,
    #                         expected_value=LinguisticVariableEnum.DECREASING)
    #          ]),
    # RuleBase(rtype=RuleTypeEnum.PERFORMANCE,
    #          channel=ChannelEnum.FACEBOOK,
    #          category=RuleCategoryEnum.IMPROVE_CPR,
    #          importance=RuleImportanceEnum.MEDIUM,
    #          source=RuleSourceEnum.DEXTER,
    #          level=LevelEnum.CAMPAIGN,
    #          action=ActionEnum.NONE,
    #          redirect=RuleRedirectEnum.CREATE_LOOKALIKE_AUDIENCE,
    #          template="Dexter has identified that your cost per result has increased lately. Have you tried creating a lookalikes "
    #                   "campaign on messenger to bring your cost down even more?",
    #          breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE,
    #                                               action_breakdown=ActionBreakdownEnum.NONE),
    #          time_interval=DaysEnum.THREE_MONTHS,
    #          connective=Connective(LogicOperatorEnum.AND),
    #          antecedents=[
    #              Antecedent(aid=1,
    #                         atype=AntecedentTypeEnum.VALUE,
    #                         metric=AvailableMetricEnum.OBJECTIVE.value,
    #                         operator=LogicOperatorEnum.EQUALS,
    #                         expected_value=ObjectiveEnum.LINK_CLICKS.value),
    #              Antecedent(aid=2,
    #                         atype=AntecedentTypeEnum.FUZZY_TREND,
    #                         metric=AvailableMetricEnum.COST_PER_RESULT.value,
    #                         operator=LogicOperatorEnum.EQUALS,
    #                         expected_value=LinguisticVariableEnum.INCREASING)
    #          ]),
    #
    # # messenger
    # RuleBase(rtype=RuleTypeEnum.CREATIVE,
    #          channel=ChannelEnum.FACEBOOK,
    #          category=RuleCategoryEnum.IMPROVE_CPR,
    #          importance=RuleImportanceEnum.MEDIUM,
    #          source=RuleSourceEnum.DEXTER,
    #          level=LevelEnum.CAMPAIGN,
    #          action=ActionEnum.NONE,
    #          redirect=RuleRedirectEnum.EDIT_STRUCTURE,
    #          template="Dexter loves good results. However, we’ve seen your results decrease lately. Have you considered "
    #                   "launching new ad copy or creatives to boost your results?",
    #          breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE,
    #                                               action_breakdown=ActionBreakdownEnum.NONE),
    #          time_interval=DaysEnum.THREE_MONTHS,
    #          connective=Connective(LogicOperatorEnum.AND),
    #          antecedents=[
    #              Antecedent(aid=1,
    #                         atype=AntecedentTypeEnum.VALUE,
    #                         metric=AvailableMetricEnum.OBJECTIVE.value,
    #                         operator=LogicOperatorEnum.EQUALS,
    #                         expected_value=ObjectiveEnum.MESSAGES.value),
    #              Antecedent(aid=2,
    #                         atype=AntecedentTypeEnum.FUZZY_TREND,
    #                         metric=AvailableMetricEnum.RESULTS.value,
    #                         operator=LogicOperatorEnum.EQUALS,
    #                         expected_value=LinguisticVariableEnum.DECREASING)
    #          ]),
    #
    # # post engagement
    # RuleBase(rtype=RuleTypeEnum.CREATIVE,
    #          channel=ChannelEnum.FACEBOOK,
    #          category=RuleCategoryEnum.IMPROVE_ENGAGEMENT,
    #          importance=RuleImportanceEnum.HIGH,
    #          source=RuleSourceEnum.DEXTER,
    #          level=LevelEnum.CAMPAIGN,
    #          action=ActionEnum.NONE,
    #          redirect=RuleRedirectEnum.CAMPAIGN_MANAGER,
    #          template="Did you know you can drastically improve your post engagement by asking a question in the first sentence of your ad? Dexter "
    #                   "suggests you make this change to help improve your results!",
    #          breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE,
    #                                               action_breakdown=ActionBreakdownEnum.NONE),
    #          time_interval=DaysEnum.THREE_MONTHS,
    #          connective=Connective(LogicOperatorEnum.AND),
    #          antecedents=[
    #              Antecedent(aid=1,
    #                         atype=AntecedentTypeEnum.VALUE,
    #                         metric=AvailableMetricEnum.OBJECTIVE.value,
    #                         operator=LogicOperatorEnum.EQUALS,
    #                         expected_value=ObjectiveEnum.POST_ENGAGEMENT.value),
    #              Antecedent(aid=2,
    #                         atype=AntecedentTypeEnum.FUZZY_TREND,
    #                         metric=AvailableMetricEnum.RESULTS.value,
    #                         operator=LogicOperatorEnum.EQUALS,
    #                         expected_value=LinguisticVariableEnum.DECREASING)
    #          ]),
    # RuleBase(rtype=RuleTypeEnum.CREATIVE,
    #          channel=ChannelEnum.FACEBOOK,
    #          category=RuleCategoryEnum.IMPROVE_ENGAGEMENT,
    #          importance=RuleImportanceEnum.HIGH,
    #          source=RuleSourceEnum.DEXTER,
    #          level=LevelEnum.CAMPAIGN,
    #          action=ActionEnum.NONE,
    #          redirect=RuleRedirectEnum.CAMPAIGN_MANAGER,
    #          template="Did you know that your cost per result will decrease as you get more post engagement on your ad? Try asking a question, "
    #                   "keeping in mind who your audience is, to further engage your audience!",
    #          breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE,
    #                                               action_breakdown=ActionBreakdownEnum.NONE),
    #          time_interval=DaysEnum.THREE_MONTHS,
    #          connective=Connective(LogicOperatorEnum.AND),
    #          antecedents=[
    #              Antecedent(aid=1,
    #                         atype=AntecedentTypeEnum.VALUE,
    #                         metric=AvailableMetricEnum.OBJECTIVE.value,
    #                         operator=LogicOperatorEnum.EQUALS,
    #                         expected_value=ObjectiveEnum.POST_ENGAGEMENT.value),
    #              Antecedent(aid=2,
    #                         atype=AntecedentTypeEnum.FUZZY_TREND,
    #                         metric=AvailableMetricEnum.COST_PER_RESULT.value,
    #                         operator=LogicOperatorEnum.EQUALS,
    #                         expected_value=LinguisticVariableEnum.DECREASING)
    #          ]),
    #
    # # catalog sales
    # RuleBase(rtype=RuleTypeEnum.PERFORMANCE,
    #          channel=ChannelEnum.FACEBOOK,
    #          category=RuleCategoryEnum.IMPROVE_ROAS,
    #          importance=RuleImportanceEnum.HIGH,
    #          source=RuleSourceEnum.DEXTER,
    #          level=LevelEnum.CAMPAIGN,
    #          action=ActionEnum.NONE,
    #          redirect=RuleRedirectEnum.CREATE_RETARGETING_AUDIENCE,
    #          template="Did you know that you can bring your cost per purchase down significantly by running retargeting campaigns? "
    #                   "Start this process now to see better results!",
    #          breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE,
    #                                               action_breakdown=ActionBreakdownEnum.NONE),
    #          time_interval=DaysEnum.THREE_MONTHS,
    #          connective=Connective(LogicOperatorEnum.AND),
    #          antecedents=[
    #              Antecedent(aid=1,
    #                         atype=AntecedentTypeEnum.VALUE,
    #                         metric=AvailableMetricEnum.OBJECTIVE.value,
    #                         operator=LogicOperatorEnum.EQUALS,
    #                         expected_value=ObjectiveEnum.PRODUCT_CATALOG_SALES.value),
    #              Antecedent(aid=2,
    #                         atype=AntecedentTypeEnum.FUZZY_TREND,
    #                         metric=AvailableMetricEnum.COST_PER_PURCHASE.value,
    #                         operator=LogicOperatorEnum.EQUALS,
    #                         expected_value=LinguisticVariableEnum.INCREASING)
    #          ]),
    # RuleBase(rtype=RuleTypeEnum.AUDIENCE,
    #          channel=ChannelEnum.FACEBOOK,
    #          category=RuleCategoryEnum.IMPROVE_ROAS,
    #          importance=RuleImportanceEnum.MEDIUM,
    #          source=RuleSourceEnum.DEXTER,
    #          level=LevelEnum.CAMPAIGN,
    #          action=ActionEnum.NONE,
    #          redirect=RuleRedirectEnum.CAMPAIGN_MANAGER,
    #          template="Your <id=1&metric_name=ROAS&metric_type=1&antecedent_type=7> has decreased <id=1&value=null> in the last <id=1&time_interval=7> days. "
    #                   "Have you optimized for the best age and gender, or looked at your best performing placement "
    #                   "to make sure your ad is set up for maximum success? ",
    #          breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE,
    #                                               action_breakdown=ActionBreakdownEnum.NONE),
    #          time_interval=DaysEnum.THREE_MONTHS,
    #          connective=Connective(LogicOperatorEnum.AND),
    #          antecedents=[
    #              Antecedent(aid=1,
    #                         atype=AntecedentTypeEnum.VALUE,
    #                         metric=AvailableMetricEnum.OBJECTIVE.value,
    #                         operator=LogicOperatorEnum.EQUALS,
    #                         expected_value=ObjectiveEnum.PRODUCT_CATALOG_SALES.value),
    #              Antecedent(aid=2,
    #                         atype=AntecedentTypeEnum.FUZZY_TREND,
    #                         metric=AvailableMetricEnum.ROAS.value,
    #                         operator=LogicOperatorEnum.EQUALS,
    #                         expected_value=LinguisticVariableEnum.DECREASING)
    #          ]),
    #
    # # reach
    # RuleBase(rtype=RuleTypeEnum.AUDIENCE,
    #          channel=ChannelEnum.FACEBOOK,
    #          category=RuleCategoryEnum.IMPROVE_CPR,
    #          importance=RuleImportanceEnum.HIGH,
    #          source=RuleSourceEnum.DEXTER,
    #          level=LevelEnum.CAMPAIGN,
    #          action=ActionEnum.NONE,
    #          redirect=RuleRedirectEnum.EDIT_STRUCTURE,
    #          template="Your reach has decreased, but why? Your relevancy score is below most likely very low, at this point your ads are being penalized "
    #                   "and delivery is being affected. Dexter suggests creating new ads with new targeting.",
    #          breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE,
    #                                               action_breakdown=ActionBreakdownEnum.NONE),
    #          time_interval=DaysEnum.THREE_MONTHS,
    #          connective=Connective(LogicOperatorEnum.AND),
    #          antecedents=[
    #              Antecedent(aid=1,
    #                         atype=AntecedentTypeEnum.VALUE,
    #                         metric=AvailableMetricEnum.OBJECTIVE.value,
    #                         operator=LogicOperatorEnum.EQUALS,
    #                         expected_value=ObjectiveEnum.REACH.value),
    #              Antecedent(aid=2,
    #                         atype=AntecedentTypeEnum.FUZZY_TREND,
    #                         metric=AvailableMetricEnum.REACH.value,
    #                         operator=LogicOperatorEnum.EQUALS,
    #                         expected_value=LinguisticVariableEnum.DECREASING)
    #          ]),
    # RuleBase(rtype=RuleTypeEnum.PERFORMANCE,
    #          channel=ChannelEnum.FACEBOOK,
    #          category=RuleCategoryEnum.IMPROVE_CPR,
    #          importance=RuleImportanceEnum.MEDIUM,
    #          source=RuleSourceEnum.DEXTER,
    #          level=LevelEnum.CAMPAIGN,
    #          action=ActionEnum.NONE,
    #          redirect=RuleRedirectEnum.EDIT_STRUCTURE,
    #          template="Your <id=1&metric_name=CPM&metric_type=1&antecedent_type=8> has increased by <id=1&value=null>% in the last "
    #                   "<id=1&time_interval=3> days. It’s one of two reasons: Your frequency is high or your ad isn’t resonating with your "
    #                   "target audience. Take a look and make the right adjustments!",
    #          breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE,
    #                                               action_breakdown=ActionBreakdownEnum.NONE),
    #          time_interval=DaysEnum.THREE_MONTHS,
    #          connective=Connective(LogicOperatorEnum.AND),
    #          antecedents=[
    #              Antecedent(aid=1,
    #                         atype=AntecedentTypeEnum.VALUE,
    #                         metric=AvailableMetricEnum.OBJECTIVE.value,
    #                         operator=LogicOperatorEnum.EQUALS,
    #                         expected_value=ObjectiveEnum.REACH.value),
    #              Antecedent(aid=2,
    #                         atype=AntecedentTypeEnum.FUZZY_VALUE,
    #                         metric=AvailableMetricEnum.CPM.value,
    #                         operator=LogicOperatorEnum.EQUALS,
    #                         expected_value=LinguisticVariableEnum.HIGH)
    #          ]),

    # video views
    # RuleBase(rtype=RuleTypeEnum.PERFORMANCE,
    #          channel=ChannelEnum.FACEBOOK,
    #          category=RuleCategoryEnum.IMPROVE_ENGAGEMENT,
    #          importance=RuleImportanceEnum.HIGH,
    #          source=RuleSourceEnum.DEXTER,
    #          level=LevelEnum.CAMPAIGN,
    #          action=ActionEnum.NONE,
    #          redirect=RuleRedirectEnum.CAMPAIGN_MANAGER,
    #          template="Your <id=1&metric_name=COST_PER_THRUPLAY&metric_type=1&antecedent_type=7> has gone up "
    #                   "id=1&value=null> over the last <id=1&time_interval=7> days. "
    #                   "Have you optimised your delivery by age and gender or for the best performing placement?",
    #          breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE,
    #                                               action_breakdown=ActionBreakdownEnum.NONE),
    #          time_interval=DaysEnum.THREE_MONTHS,
    #          connective=Connective(LogicOperatorEnum.AND),
    #          antecedents=[
    #              Antecedent(aid=1,
    #                         atype=AntecedentTypeEnum.VALUE,
    #                         metric=AvailableMetricEnum.OBJECTIVE.value,
    #                         operator=LogicOperatorEnum.EQUALS,
    #                         expected_value=ObjectiveEnum.VIDEO_VIEWS.value),
    #              Antecedent(aid=2,
    #                         atype=AntecedentTypeEnum.FUZZY_TREND,
    #                         metric=AvailableMetricEnum.COST_PER_THRUPLAY.value,
    #                         operator=LogicOperatorEnum.EQUALS,
    #                         expected_value=LinguisticVariableEnum.INCREASING)
    #          ]),
    # RuleBase(rtype=RuleTypeEnum.CREATIVE,
    #          channel=ChannelEnum.FACEBOOK,
    #          category=RuleCategoryEnum.IMPROVE_ENGAGEMENT,
    #          importance=RuleImportanceEnum.HIGH,
    #          source=RuleSourceEnum.DEXTER,
    #          level=LevelEnum.CAMPAIGN,
    #          action=ActionEnum.NONE,
    #          redirect=RuleRedirectEnum.EDIT_STRUCTURE,
    #          template="Your videos are smashing it and your cost per play is really competitive. Have you tried creating more videos for other "
    #                   "campaigns that you're running?",
    #          breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE,
    #                                               action_breakdown=ActionBreakdownEnum.NONE),
    #          time_interval=DaysEnum.THREE_MONTHS,
    #          connective=Connective(LogicOperatorEnum.AND),
    #          antecedents=[
    #              Antecedent(aid=1,
    #                         atype=AntecedentTypeEnum.VALUE,
    #                         metric=AvailableMetricEnum.OBJECTIVE.value,
    #                         operator=LogicOperatorEnum.EQUALS,
    #                         expected_value=ObjectiveEnum.VIDEO_VIEWS.value),
    #              Antecedent(aid=2,
    #                         atype=AntecedentTypeEnum.FUZZY_TREND,
    #                         metric=AvailableMetricEnum.COST_PER_THRUPLAY.value,
    #                         operator=LogicOperatorEnum.EQUALS,
    #                         expected_value=LinguisticVariableEnum.DECREASING),
    #              Antecedent(aid=3,
    #                         atype=AntecedentTypeEnum.FUZZY_TREND,
    #                         metric=AvailableMetricEnum.VIDEO_PLAYS.value,
    #                         operator=LogicOperatorEnum.EQUALS,
    #                         expected_value=LinguisticVariableEnum.INCREASING)
    #          ]),
]
