apiVersion: v1
kind: Service
metadata:
  name: prod-filed-potter-facebook-pixels-api
  labels:
    run: prod-filed-potter-facebook-pixels-api
spec:
  ports:
  - port: 47250
  selector:
    run: prod-filed-potter-facebook-pixels-api