from GoogleTuring.Api.Catalogs.Views.ViewColumnsMaster.DimensionColumnsBase import DimensionColumnsBase
from GoogleTuring.Api.Catalogs.Views.ViewColumnsMaster.DimensionColumnsMaster import DimensionColumnsMaster


class CampaignDimensionColumnsMaster(DimensionColumnsBase):
    DIMENSIONS = [
        DimensionColumnsMaster.account_currency_code,
        DimensionColumnsMaster.account_descriptive_name,
        DimensionColumnsMaster.account_time_zone,
        DimensionColumnsMaster.advertising_channel_sub_type,
        DimensionColumnsMaster.advertising_channel_type,
        DimensionColumnsMaster.amount,
        DimensionColumnsMaster.base_campaign_id,
        DimensionColumnsMaster.bidding_strategy_id,
        DimensionColumnsMaster.bidding_strategy_name,
        DimensionColumnsMaster.bidding_strategy_type,
        DimensionColumnsMaster.budget_id,
        DimensionColumnsMaster.campaign_desktop_bid_modifier,
        DimensionColumnsMaster.campaign_group_id,
        DimensionColumnsMaster.campaign_id,
        DimensionColumnsMaster.campaign_mobile_bid_modifier,
        DimensionColumnsMaster.campaign_name,
        DimensionColumnsMaster.campaign_status,
        DimensionColumnsMaster.campaign_tablet_bid_modifier,
        DimensionColumnsMaster.campaign_trial_type,
        DimensionColumnsMaster.conversion_adjustment,
        DimensionColumnsMaster.customer_descriptive_name,
        DimensionColumnsMaster.end_date,
        DimensionColumnsMaster.enhanced_cpc_enabled,
        DimensionColumnsMaster.external_customer_id,
        DimensionColumnsMaster.final_url_suffix,
        DimensionColumnsMaster.has_recommended_budget,
        DimensionColumnsMaster.is_budget_explicitly_shared,
        DimensionColumnsMaster.label_ids,
        DimensionColumnsMaster.labels,
        DimensionColumnsMaster.maximize_conversion_value_target_roas,
        DimensionColumnsMaster.period,
        DimensionColumnsMaster.recommended_budget_amount,
        DimensionColumnsMaster.serving_status,
        DimensionColumnsMaster.start_date,
        DimensionColumnsMaster.total_amount,
        DimensionColumnsMaster.tracking_url_template,
        DimensionColumnsMaster.url_custom_parameters,
    ]
