import typing

from FacebookDexter.Engine.Algorithms.FuzzyRuleBasedOptimization.Metrics.AvailableMetricEnum import AvailableMetricEnum
from FacebookDexter.Infrastructure.Domain.Actions.ActionDetailsBuilder import ActionEnum
from FacebookDexter.Infrastructure.Domain.Breakdowns import BreakdownMetadata, BreakdownEnum, ActionBreakdownEnum
from FacebookDexter.Infrastructure.Domain.ChannelEnum import ChannelEnum
from FacebookDexter.Infrastructure.Domain.DaysEnum import DaysEnum
from FacebookDexter.Infrastructure.Domain.LevelEnums import LevelEnum
from FacebookDexter.Infrastructure.Domain.ObjectiveEnum import ObjectiveEnum
from FacebookDexter.Infrastructure.Domain.Rules.AntecedentEnums import AntecedentTypeEnum
from FacebookDexter.Infrastructure.Domain.Rules.RuleBase import RuleBase, Antecedent, LogicOperatorEnum
from FacebookDexter.Infrastructure.Domain.Rules.RuleEnums import RuleTypeEnum, RuleCategoryEnum, RuleImportanceEnum, RuleSourceEnum
from FacebookDexter.Infrastructure.FuzzyEngine.FuzzySets.FuzzySets import LinguisticVariableEnum


class Rules:
    remove = [
        RuleBase(rtype=RuleTypeEnum.PERFORMANCE,
                 channel=ChannelEnum.FACEBOOK,
                 category=RuleCategoryEnum.IMPROVE_CPR,
                 importance=RuleImportanceEnum.HIGH,
                 source=RuleSourceEnum.DEXTER,
                 level=LevelEnum.AD,
                 action=ActionEnum.PAUSE,
                 template="Dexter noticed that results are decreasing for age group {age_group_value}. You should remove this age group from your targeting.",
                 breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.AGE, action_breakdown=ActionBreakdownEnum.NONE),
                 time_interval=DaysEnum.THREE_MONTHS,
                 connective=LogicOperatorEnum.AND,
                 antecedents=[
                     Antecedent(aid=1,
                                atype=AntecedentTypeEnum.VALUE,
                                metric=AvailableMetricEnum.OBJECTIVE.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=ObjectiveEnum.APP_INSTALLS.value),
                     Antecedent(aid=2,
                                atype=AntecedentTypeEnum.FUZZY_TREND,
                                metric=AvailableMetricEnum.RESULTS.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=LinguisticVariableEnum.DECREASING)
                 ])
    ]

    pause = [
        RuleBase(rtype=RuleTypeEnum.PERFORMANCE,
                 channel=ChannelEnum.FACEBOOK,
                 category=RuleCategoryEnum.IMPROVE_CPR,
                 importance=RuleImportanceEnum.HIGH,
                 source=RuleSourceEnum.DEXTER,
                 level=LevelEnum.AD,
                 action=ActionEnum.PAUSE,
                 template="Dexter noticed your CPC increased while your results remain low. You should pause this ad to improve performance.",
                 breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE, action_breakdown=ActionBreakdownEnum.NONE),
                 time_interval=DaysEnum.THREE_MONTHS,
                 connective=LogicOperatorEnum.AND,
                 antecedents=[
                     Antecedent(aid=1,
                                atype=AntecedentTypeEnum.VALUE,
                                metric=AvailableMetricEnum.OBJECTIVE.value,
                                operator=LogicOperatorEnum.NOT_EQUAL,
                                expected_value=ObjectiveEnum.REACH.value),
                     Antecedent(aid=2,
                                atype=AntecedentTypeEnum.FUZZY_TREND,
                                metric=AvailableMetricEnum.CPC.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=LinguisticVariableEnum.INCREASING),
                     Antecedent(aid=3,
                                atype=AntecedentTypeEnum.FUZZY_VALUE,
                                metric=AvailableMetricEnum.RESULTS.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=LinguisticVariableEnum.LOW)
                 ]),
        RuleBase(rtype=RuleTypeEnum.PERFORMANCE,
                 channel=ChannelEnum.FACEBOOK,
                 category=RuleCategoryEnum.IMPROVE_CPR,
                 importance=RuleImportanceEnum.HIGH,
                 source=RuleSourceEnum.DEXTER,
                 level=LevelEnum.AD,
                 action=ActionEnum.PAUSE,
                 template="Dexter noticed your impressions increased while your results remain low. You should pause this ad to improve performance.",
                 breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE, action_breakdown=ActionBreakdownEnum.NONE),
                 time_interval=DaysEnum.THREE_MONTHS,
                 connective=LogicOperatorEnum.AND,
                 antecedents=[
                     Antecedent(aid=1,
                                atype=AntecedentTypeEnum.VALUE,
                                metric=AvailableMetricEnum.OBJECTIVE.value,
                                operator=LogicOperatorEnum.NOT_EQUAL,
                                expected_value=ObjectiveEnum.REACH.value),
                     Antecedent(aid=2,
                                atype=AntecedentTypeEnum.FUZZY_TREND,
                                metric=AvailableMetricEnum.IMPRESSIONS.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=LinguisticVariableEnum.INCREASING),
                     Antecedent(aid=3,
                                atype=AntecedentTypeEnum.FUZZY_VALUE,
                                metric=AvailableMetricEnum.RESULTS.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=LinguisticVariableEnum.LOW)
                 ]),
        RuleBase(rtype=RuleTypeEnum.PERFORMANCE,
                 channel=ChannelEnum.FACEBOOK,
                 category=RuleCategoryEnum.IMPROVE_CPR,
                 importance=RuleImportanceEnum.HIGH,
                 source=RuleSourceEnum.DEXTER,
                 level=LevelEnum.AD,
                 action=ActionEnum.PAUSE,
                 template="Dexter noticed your cost per result is at historical high levels. You should pause this ad to improve performance.",
                 breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE, action_breakdown=ActionBreakdownEnum.NONE),
                 time_interval=DaysEnum.THREE_MONTHS,
                 connective=LogicOperatorEnum.AND,
                 antecedents=[
                     Antecedent(aid=1,
                                atype=AntecedentTypeEnum.VALUE,
                                metric=AvailableMetricEnum.OBJECTIVE.value,
                                operator=LogicOperatorEnum.NOT_EQUAL,
                                expected_value=ObjectiveEnum.REACH.value),
                     Antecedent(aid=2,
                                atype=AntecedentTypeEnum.FUZZY_TREND,
                                metric=AvailableMetricEnum.COST_PER_RESULT.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=LinguisticVariableEnum.HIGH)
                 ]),
        RuleBase(rtype=RuleTypeEnum.PERFORMANCE,
                 channel=ChannelEnum.FACEBOOK,
                 category=RuleCategoryEnum.IMPROVE_CPR,
                 importance=RuleImportanceEnum.HIGH,
                 source=RuleSourceEnum.DEXTER,
                 level=LevelEnum.AD,
                 action=ActionEnum.PAUSE,
                 template="Dexter noticed your CTR is decreasing while your results remain low. You should pause this ad to improve performance.",
                 breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE, action_breakdown=ActionBreakdownEnum.NONE),
                 time_interval=DaysEnum.THREE_MONTHS,
                 connective=LogicOperatorEnum.AND,
                 antecedents=[
                     Antecedent(aid=1,
                                atype=AntecedentTypeEnum.FUZZY_TREND,
                                metric=AvailableMetricEnum.CTR.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=LinguisticVariableEnum.DECREASING),
                     Antecedent(aid=2,
                                atype=AntecedentTypeEnum.FUZZY_VALUE,
                                metric=AvailableMetricEnum.RESULTS.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=LinguisticVariableEnum.LOW)
                 ]),
    ]

    decrease_budget = [
        RuleBase(rtype=RuleTypeEnum.BUDGET_AND_BID,
                 channel=ChannelEnum.FACEBOOK,
                 category=RuleCategoryEnum.IMPROVE_CPR,
                 importance=RuleImportanceEnum.HIGH,
                 source=RuleSourceEnum.DEXTER,
                 level=LevelEnum.AD,
                 action=ActionEnum.NONE,
                 template="Dexter noticed your CPR increased while your CTR remains low. You should decrease the budget by maximum 25%.",
                 breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE, action_breakdown=ActionBreakdownEnum.NONE),
                 time_interval=DaysEnum.THREE_MONTHS,
                 connective=LogicOperatorEnum.AND,
                 antecedents=[
                     Antecedent(aid=1,
                                atype=AntecedentTypeEnum.FUZZY_TREND,
                                metric=AvailableMetricEnum.COST_PER_RESULT.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=LinguisticVariableEnum.INCREASING),
                     Antecedent(aid=2,
                                atype=AntecedentTypeEnum.FUZZY_VALUE,
                                metric=AvailableMetricEnum.CTR.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=LinguisticVariableEnum.LOW)
                 ]),
        RuleBase(rtype=RuleTypeEnum.BUDGET_AND_BID,
                 channel=ChannelEnum.FACEBOOK,
                 category=RuleCategoryEnum.IMPROVE_CPR,
                 importance=RuleImportanceEnum.HIGH,
                 source=RuleSourceEnum.DEXTER,
                 level=LevelEnum.AD,
                 action=ActionEnum.NONE,
                 template="Dexter noticed your CPR increased while your conversions remains low. You should decrease the budget by maximum 25%.",
                 breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE, action_breakdown=ActionBreakdownEnum.NONE),
                 time_interval=DaysEnum.THREE_MONTHS,
                 connective=LogicOperatorEnum.AND,
                 antecedents=[
                     Antecedent(aid=1,
                                atype=AntecedentTypeEnum.FUZZY_TREND,
                                metric=AvailableMetricEnum.COST_PER_RESULT.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=LinguisticVariableEnum.INCREASING),
                     Antecedent(aid=2,
                                atype=AntecedentTypeEnum.FUZZY_VALUE,
                                metric=AvailableMetricEnum.CONVERSIONS.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=LinguisticVariableEnum.LOW)
                 ]),
        RuleBase(rtype=RuleTypeEnum.BUDGET_AND_BID,
                 channel=ChannelEnum.FACEBOOK,
                 category=RuleCategoryEnum.IMPROVE_CPR,
                 importance=RuleImportanceEnum.HIGH,
                 source=RuleSourceEnum.DEXTER,
                 level=LevelEnum.AD,
                 action=ActionEnum.NONE,
                 template="Dexter noticed your relevancy score and results are low. You should decrease the budget by maximum 25%.",
                 breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE, action_breakdown=ActionBreakdownEnum.NONE),
                 time_interval=DaysEnum.THREE_MONTHS,
                 connective=LogicOperatorEnum.AND,
                 antecedents=[
                     Antecedent(aid=1,
                                atype=AntecedentTypeEnum.FUZZY_VALUE,
                                metric=AvailableMetricEnum.RESULTS.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=LinguisticVariableEnum.LOW),
                     Antecedent(aid=2,
                                atype=AntecedentTypeEnum.FUZZY_VALUE,
                                metric=AvailableMetricEnum.RELEVANCY_SCORE.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=LinguisticVariableEnum.LOW)
                 ]),
        RuleBase(rtype=RuleTypeEnum.BUDGET_AND_BID,
                 channel=ChannelEnum.FACEBOOK,
                 category=RuleCategoryEnum.IMPROVE_CPR,
                 importance=RuleImportanceEnum.HIGH,
                 source=RuleSourceEnum.DEXTER,
                 level=LevelEnum.AD,
                 action=ActionEnum.NONE,
                 template="Dexter noticed your relevancy score is low while your CPC remains high. You should decrease the budget by maximum 25%.",
                 breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE, action_breakdown=ActionBreakdownEnum.NONE),
                 time_interval=DaysEnum.THREE_MONTHS,
                 connective=LogicOperatorEnum.AND,
                 antecedents=[
                     Antecedent(aid=1,
                                atype=AntecedentTypeEnum.FUZZY_VALUE,
                                metric=AvailableMetricEnum.CPC.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=LinguisticVariableEnum.HIGH),
                     Antecedent(aid=2,
                                atype=AntecedentTypeEnum.FUZZY_VALUE,
                                metric=AvailableMetricEnum.RELEVANCY_SCORE.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=LinguisticVariableEnum.LOW)
                 ])
    ]

    increase_budget = [
        RuleBase(rtype=RuleTypeEnum.BUDGET_AND_BID,
                 channel=ChannelEnum.FACEBOOK,
                 category=RuleCategoryEnum.IMPROVE_CPR,
                 importance=RuleImportanceEnum.HIGH,
                 source=RuleSourceEnum.DEXTER,
                 level=LevelEnum.AD,
                 action=ActionEnum.NONE,
                 template="Dexter noticed your relevancy score is high and results are good. You should increase the budget by maximum 25%.",
                 breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE, action_breakdown=ActionBreakdownEnum.NONE),
                 time_interval=DaysEnum.THREE_MONTHS,
                 connective=LogicOperatorEnum.AND,
                 antecedents=[
                     Antecedent(aid=1,
                                atype=AntecedentTypeEnum.FUZZY_VALUE,
                                metric=AvailableMetricEnum.RELEVANCY_SCORE.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=LinguisticVariableEnum.HIGH),
                     Antecedent(aid=2,
                                atype=AntecedentTypeEnum.FUZZY_VALUE,
                                metric=AvailableMetricEnum.RESULTS.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=LinguisticVariableEnum.HIGH)
                 ]),
        RuleBase(rtype=RuleTypeEnum.BUDGET_AND_BID,
                 channel=ChannelEnum.FACEBOOK,
                 category=RuleCategoryEnum.IMPROVE_CPR,
                 importance=RuleImportanceEnum.HIGH,
                 source=RuleSourceEnum.DEXTER,
                 level=LevelEnum.AD,
                 action=ActionEnum.NONE,
                 template="Dexter noticed your cost per result is low while getting good conversions. You should increase the budget by maximum 25%.",
                 breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE, action_breakdown=ActionBreakdownEnum.NONE),
                 time_interval=DaysEnum.THREE_MONTHS,
                 connective=LogicOperatorEnum.AND,
                 antecedents=[
                     Antecedent(aid=1,
                                atype=AntecedentTypeEnum.FUZZY_VALUE,
                                metric=AvailableMetricEnum.COST_PER_RESULT.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=LinguisticVariableEnum.LOW),
                     Antecedent(aid=2,
                                atype=AntecedentTypeEnum.FUZZY_VALUE,
                                metric=AvailableMetricEnum.CONVERSIONS.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=LinguisticVariableEnum.HIGH)
                 ]),
        RuleBase(rtype=RuleTypeEnum.BUDGET_AND_BID,
                 channel=ChannelEnum.FACEBOOK,
                 category=RuleCategoryEnum.IMPROVE_CPR,
                 importance=RuleImportanceEnum.HIGH,
                 source=RuleSourceEnum.DEXTER,
                 level=LevelEnum.AD,
                 action=ActionEnum.NONE,
                 template="Dexter noticed your CTR and conversion rate are both increasing. You should increase the budget by maximum 25%.",
                 breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE, action_breakdown=ActionBreakdownEnum.NONE),
                 time_interval=DaysEnum.THREE_MONTHS,
                 connective=LogicOperatorEnum.AND,
                 antecedents=[
                     Antecedent(aid=1,
                                atype=AntecedentTypeEnum.FUZZY_TREND,
                                metric=AvailableMetricEnum.CTR.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=LinguisticVariableEnum.INCREASING),
                     Antecedent(aid=2,
                                atype=AntecedentTypeEnum.FUZZY_TREND,
                                metric=AvailableMetricEnum.CONVERSION_RATE.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=LinguisticVariableEnum.INCREASING)
                 ]),
    ]

    general = [
        # App Installs
        RuleBase(rtype=RuleTypeEnum.CREATIVE,
                 channel=ChannelEnum.FACEBOOK,
                 category=RuleCategoryEnum.IMPROVE_CPR,
                 importance=RuleImportanceEnum.HIGH,
                 source=RuleSourceEnum.DEXTER,
                 level=LevelEnum.CAMPAIGN,
                 action=ActionEnum.NONE,
                 template="Your app install results are decreasing {week}. Dexter recommends AB testing new ad copy or new creatives to drive a better "
                          "results with your app installs.",
                 breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE, action_breakdown=ActionBreakdownEnum.NONE),
                 time_interval=DaysEnum.THREE_MONTHS,
                 connective=LogicOperatorEnum.AND,
                 antecedents=[
                     Antecedent(aid=1,
                                atype=AntecedentTypeEnum.VALUE,
                                metric=AvailableMetricEnum.OBJECTIVE.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=ObjectiveEnum.APP_INSTALLS.value),
                     Antecedent(aid=2,
                                atype=AntecedentTypeEnum.FUZZY_TREND,
                                metric=AvailableMetricEnum.RESULTS.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=LinguisticVariableEnum.DECREASING)
                 ]),
        RuleBase(rtype=RuleTypeEnum.CREATIVE,
                 channel=ChannelEnum.FACEBOOK,
                 category=RuleCategoryEnum.IMPROVE_CPC,
                 importance=RuleImportanceEnum.HIGH,
                 source=RuleSourceEnum.DEXTER,
                 level=LevelEnum.CAMPAIGN,
                 action=ActionEnum.NONE,
                 template="Your Cost Per Install has increased by {value}. Dexter recommends combining your best performing ad copy and creatives to decrease"
                          " your cost per install.",
                 breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE, action_breakdown=ActionBreakdownEnum.NONE),
                 time_interval=DaysEnum.THREE_MONTHS,
                 connective=LogicOperatorEnum.AND,
                 antecedents=[
                     Antecedent(aid=1,
                                atype=AntecedentTypeEnum.VALUE,
                                metric=AvailableMetricEnum.OBJECTIVE.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=ObjectiveEnum.APP_INSTALLS.value),
                     Antecedent(aid=2,
                                atype=AntecedentTypeEnum.FUZZY_TREND,
                                metric=AvailableMetricEnum.COST_PER_APP_INSTALL.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=LinguisticVariableEnum.INCREASING)
                 ]),
        RuleBase(rtype=RuleTypeEnum.AUDIENCE,
                 channel=ChannelEnum.FACEBOOK,
                 category=RuleCategoryEnum.IMPROVE_CPC,
                 importance=RuleImportanceEnum.MEDIUM,
                 source=RuleSourceEnum.DEXTER,
                 level=LevelEnum.ADSET,
                 action=ActionEnum.NONE,
                 template="Your CPM has increased too much for Dexter. This could mean several things. However, Dexter suggests that you launch your best "
                          "performing ads with {interests}. ",
                 breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE, action_breakdown=ActionBreakdownEnum.NONE),
                 time_interval=DaysEnum.THREE_MONTHS,
                 connective=LogicOperatorEnum.AND,
                 antecedents=[
                     Antecedent(aid=1,
                                atype=AntecedentTypeEnum.VALUE,
                                metric=AvailableMetricEnum.OBJECTIVE.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=ObjectiveEnum.APP_INSTALLS.value),
                     Antecedent(aid=2,
                                atype=AntecedentTypeEnum.FUZZY_TREND,
                                metric=AvailableMetricEnum.CPM.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=LinguisticVariableEnum.INCREASING)
                 ]),
        RuleBase(rtype=RuleTypeEnum.CREATIVE,
                 channel=ChannelEnum.FACEBOOK,
                 category=RuleCategoryEnum.IMPROVE_CPC,
                 importance=RuleImportanceEnum.LOW,
                 source=RuleSourceEnum.DEXTER,
                 level=LevelEnum.CAMPAIGN,
                 action=ActionEnum.NONE,
                 template="Your ad frequency on your campaign is near or above 3.0, which is when ads start to lose their effectiveness. Dexter suggests "
                          "launching new ad creatives to help bring the score back down.",
                 breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE, action_breakdown=ActionBreakdownEnum.NONE),
                 time_interval=DaysEnum.THREE_MONTHS,
                 connective=LogicOperatorEnum.AND,
                 antecedents=[
                     Antecedent(aid=1,
                                atype=AntecedentTypeEnum.VALUE,
                                metric=AvailableMetricEnum.OBJECTIVE.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=ObjectiveEnum.APP_INSTALLS.value),
                     Antecedent(aid=2,
                                atype=AntecedentTypeEnum.FUZZY_VALUE,
                                metric=AvailableMetricEnum.FREQUENCY.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=LinguisticVariableEnum.HIGH)
                 ]),

        # Brand awareness
        RuleBase(rtype=RuleTypeEnum.BUDGET_AND_BID,
                 channel=ChannelEnum.FACEBOOK,
                 category=RuleCategoryEnum.OPTIMIZE_BUDGET,
                 importance=RuleImportanceEnum.HIGH,
                 source=RuleSourceEnum.DEXTER,
                 level=LevelEnum.CAMPAIGN,
                 action=ActionEnum.NONE,
                 template="You’re reaching tons of new people each day, {reach} to be exact. Your cost per click is relatively stable, too. Dexter suggests "
                          "increasing your budget by 25%.",
                 breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE, action_breakdown=ActionBreakdownEnum.NONE),
                 time_interval=DaysEnum.THREE_MONTHS,
                 connective=LogicOperatorEnum.AND,
                 antecedents=[
                     Antecedent(aid=1,
                                atype=AntecedentTypeEnum.VALUE,
                                metric=AvailableMetricEnum.OBJECTIVE.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=ObjectiveEnum.BRAND_AWARENESS.value),
                     Antecedent(aid=2,
                                atype=AntecedentTypeEnum.FUZZY_TREND,
                                metric=AvailableMetricEnum.REACH.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=LinguisticVariableEnum.INCREASING)
                 ]),
        RuleBase(rtype=RuleTypeEnum.AUDIENCE,
                 channel=ChannelEnum.FACEBOOK,
                 category=RuleCategoryEnum.OPTIMIZE_TARGETING,
                 importance=RuleImportanceEnum.MEDIUM,
                 source=RuleSourceEnum.DEXTER,
                 level=LevelEnum.ADSET,
                 action=ActionEnum.NONE,
                 template="Dexter has been monitoring your campaigns very closely, and your CPM has increased by {value}. He recommends you try these new "
                          "interests {interests}, to find the cheapest cost between interests that are similar. ",
                 breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE, action_breakdown=ActionBreakdownEnum.NONE),
                 time_interval=DaysEnum.THREE_MONTHS,
                 connective=LogicOperatorEnum.AND,
                 antecedents=[
                     Antecedent(aid=1,
                                atype=AntecedentTypeEnum.VALUE,
                                metric=AvailableMetricEnum.OBJECTIVE.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=ObjectiveEnum.BRAND_AWARENESS.value),
                     Antecedent(aid=2,
                                atype=AntecedentTypeEnum.FUZZY_TREND,
                                metric=AvailableMetricEnum.CPM.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=LinguisticVariableEnum.INCREASING)
                 ]),
        RuleBase(rtype=RuleTypeEnum.PERFORMANCE,
                 channel=ChannelEnum.FACEBOOK,
                 category=RuleCategoryEnum.IMPROVE_ENGAGEMENT,
                 importance=RuleImportanceEnum.LOW,
                 source=RuleSourceEnum.DEXTER,
                 level=LevelEnum.CAMPAIGN,
                 action=ActionEnum.NONE,
                 template="Your campaign isn’t receiving much engagement. More engagement on brand awareness campaigns helps deliver ads for a reduced cost, "
                          "so Dexter suggests asking a question in the first part of the adcopy to create more engagement.",
                 breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE, action_breakdown=ActionBreakdownEnum.NONE),
                 time_interval=DaysEnum.THREE_MONTHS,
                 connective=LogicOperatorEnum.AND,
                 antecedents=[
                     Antecedent(aid=1,
                                atype=AntecedentTypeEnum.VALUE,
                                metric=AvailableMetricEnum.OBJECTIVE.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=ObjectiveEnum.BRAND_AWARENESS.value),
                     Antecedent(aid=2,
                                atype=AntecedentTypeEnum.FUZZY_TREND,
                                metric=AvailableMetricEnum.ENGAGEMENT_RATE.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=LinguisticVariableEnum.DECREASING)
                 ]),

        # Conversions
        RuleBase(rtype=RuleTypeEnum.AUDIENCE,
                 channel=ChannelEnum.FACEBOOK,
                 category=RuleCategoryEnum.IMPROVE_CONVERSION_RATE,
                 importance=RuleImportanceEnum.HIGH,
                 source=RuleSourceEnum.DEXTER,
                 level=LevelEnum.ADSET,
                 action=ActionEnum.NONE,
                 template="Your conversions have decreased over the last {days}. Dexter suggests testing {interests} to help broaden your reach and get more "
                          "results.",
                 breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE, action_breakdown=ActionBreakdownEnum.NONE),
                 time_interval=DaysEnum.THREE_MONTHS,
                 connective=LogicOperatorEnum.AND,
                 antecedents=[
                     Antecedent(aid=1,
                                atype=AntecedentTypeEnum.VALUE,
                                metric=AvailableMetricEnum.OBJECTIVE.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=ObjectiveEnum.CONVERSIONS.value),
                     Antecedent(aid=2,
                                atype=AntecedentTypeEnum.FUZZY_TREND,
                                metric=AvailableMetricEnum.RESULTS.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=LinguisticVariableEnum.DECREASING)
                 ]),
        RuleBase(rtype=RuleTypeEnum.CREATIVE,
                 channel=ChannelEnum.FACEBOOK,
                 category=RuleCategoryEnum.IMPROVE_CPR,
                 importance=RuleImportanceEnum.HIGH,
                 source=RuleSourceEnum.DEXTER,
                 level=LevelEnum.CAMPAIGN,
                 action=ActionEnum.NONE,
                 template="Your cost per result has increased {percentage} in last {days}. Have you tried targeting a more specific audience and excluding "
                          "audiences you know won't work or who have converted already?",
                 breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE, action_breakdown=ActionBreakdownEnum.NONE),
                 time_interval=DaysEnum.THREE_MONTHS,
                 connective=LogicOperatorEnum.AND,
                 antecedents=[
                     Antecedent(aid=1,
                                atype=AntecedentTypeEnum.VALUE,
                                metric=AvailableMetricEnum.OBJECTIVE.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=ObjectiveEnum.CONVERSIONS.value),
                     Antecedent(aid=2,
                                atype=AntecedentTypeEnum.FUZZY_TREND,
                                metric=AvailableMetricEnum.COST_PER_RESULT.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=LinguisticVariableEnum.INCREASING)
                 ]),
        RuleBase(rtype=RuleTypeEnum.PERFORMANCE,
                 channel=ChannelEnum.FACEBOOK,
                 category=RuleCategoryEnum.IMPROVE_ROAS,
                 importance=RuleImportanceEnum.MEDIUM,
                 source=RuleSourceEnum.DEXTER,
                 level=LevelEnum.CAMPAIGN,
                 action=ActionEnum.NONE,
                 template="Your ROAS has decreased to {roas_current_value}. We suggest you consider using lookalike audiences or custom audiences to "
                          "increase your score.",
                 breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE, action_breakdown=ActionBreakdownEnum.NONE),
                 time_interval=DaysEnum.THREE_MONTHS,
                 connective=LogicOperatorEnum.AND,
                 antecedents=[
                     Antecedent(aid=1,
                                atype=AntecedentTypeEnum.VALUE,
                                metric=AvailableMetricEnum.OBJECTIVE.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=ObjectiveEnum.CONVERSIONS.value),
                     Antecedent(aid=2,
                                atype=AntecedentTypeEnum.FUZZY_TREND,
                                metric=AvailableMetricEnum.ROAS.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=LinguisticVariableEnum.DECREASING)
                 ]),
        RuleBase(rtype=RuleTypeEnum.CREATIVE,
                 channel=ChannelEnum.FACEBOOK,
                 category=RuleCategoryEnum.IMPROVE_CONVERSION_RATE,
                 importance=RuleImportanceEnum.LOW,
                 source=RuleSourceEnum.DEXTER,
                 level=LevelEnum.CAMPAIGN,
                 action=ActionEnum.NONE,
                 template="Your conversion rate has fallen {conversion_rate_percent_variation} over the last {days}. Dexter knows video is king right now and "
                          "is proven to help with results. Have you tried uploading a video? Try it now!",
                 breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE, action_breakdown=ActionBreakdownEnum.NONE),
                 time_interval=DaysEnum.THREE_MONTHS,
                 connective=LogicOperatorEnum.AND,
                 antecedents=[
                     Antecedent(aid=1,
                                atype=AntecedentTypeEnum.VALUE,
                                metric=AvailableMetricEnum.OBJECTIVE.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=ObjectiveEnum.CONVERSIONS.value),
                     Antecedent(aid=2,
                                atype=AntecedentTypeEnum.FUZZY_TREND,
                                metric=AvailableMetricEnum.CONVERSION_RATE.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=LinguisticVariableEnum.DECREASING)
                 ]),

        # Event responses
        RuleBase(rtype=RuleTypeEnum.AUDIENCE,
                 channel=ChannelEnum.FACEBOOK,
                 category=RuleCategoryEnum.OPTIMIZE_TARGETING,
                 importance=RuleImportanceEnum.HIGH,
                 source=RuleSourceEnum.DEXTER,
                 level=LevelEnum.ADSET,
                 action=ActionEnum.NONE,
                 template="Dexter sees your RSVPs are decreasing {days}. Have you tried opening up your targeting to be broader? Dexter suggests targeting "
                          "these interests {interests} to get started.",
                 breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE, action_breakdown=ActionBreakdownEnum.NONE),
                 time_interval=DaysEnum.THREE_MONTHS,
                 connective=LogicOperatorEnum.AND,
                 antecedents=[
                     Antecedent(aid=1,
                                atype=AntecedentTypeEnum.VALUE,
                                metric=AvailableMetricEnum.OBJECTIVE.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=ObjectiveEnum.EVENT_RESPONSES.value),
                     Antecedent(aid=2,
                                atype=AntecedentTypeEnum.FUZZY_TREND,
                                metric=AvailableMetricEnum.RSVPS.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=LinguisticVariableEnum.DECREASING)
                 ]),
        RuleBase(rtype=RuleTypeEnum.AUDIENCE,
                 channel=ChannelEnum.FACEBOOK,
                 category=RuleCategoryEnum.OPTIMIZE_TARGETING,
                 importance=RuleImportanceEnum.HIGH,
                 source=RuleSourceEnum.DEXTER,
                 level=LevelEnum.ADSET,
                 action=ActionEnum.NONE,
                 template="Your cost per result has increased {cost_per_result_percentage} in the last {days}. Dexter thinks you should add more interests in "
                          "your targeting. Add these suggested interests {interests} to get started.",
                 breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE, action_breakdown=ActionBreakdownEnum.NONE),
                 time_interval=DaysEnum.THREE_MONTHS,
                 connective=LogicOperatorEnum.AND,
                 antecedents=[
                     Antecedent(aid=1,
                                atype=AntecedentTypeEnum.VALUE,
                                metric=AvailableMetricEnum.OBJECTIVE.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=ObjectiveEnum.EVENT_RESPONSES.value),
                     Antecedent(aid=2,
                                atype=AntecedentTypeEnum.FUZZY_TREND,
                                metric=AvailableMetricEnum.COST_PER_RESULT.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=LinguisticVariableEnum.INCREASING)
                 ]),

        # Lead generation
        RuleBase(rtype=RuleTypeEnum.BUDGET_AND_BID,
                 channel=ChannelEnum.FACEBOOK,
                 category=RuleCategoryEnum.OPTIMIZE_BUDGET,
                 importance=RuleImportanceEnum.HIGH,
                 source=RuleSourceEnum.DEXTER,
                 level=LevelEnum.ADSET,
                 action=ActionEnum.NONE,
                 template="We love a steady flow of leads on the cheap. Nice work on your lead gen campaign, you're smashing it! Dexter suggests you "
                          "increase your budget by 25% to maximize those leads!",
                 breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE, action_breakdown=ActionBreakdownEnum.NONE),
                 time_interval=DaysEnum.THREE_MONTHS,
                 connective=LogicOperatorEnum.AND,
                 antecedents=[
                     Antecedent(aid=1,
                                atype=AntecedentTypeEnum.VALUE,
                                metric=AvailableMetricEnum.OBJECTIVE.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=ObjectiveEnum.LEAD_GENERATION.value),
                     Antecedent(aid=2,
                                atype=AntecedentTypeEnum.FUZZY_TREND,
                                metric=AvailableMetricEnum.LEADS.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=LinguisticVariableEnum.INCREASING)
                 ]),
        RuleBase(rtype=RuleTypeEnum.PERFORMANCE,
                 channel=ChannelEnum.FACEBOOK,
                 category=RuleCategoryEnum.IMPROVE_CPR,
                 importance=RuleImportanceEnum.HIGH,
                 source=RuleSourceEnum.DEXTER,
                 level=LevelEnum.CAMPAIGN,
                 action=ActionEnum.NONE,
                 template="Your cost per result has fallen {cost_per_result_percentage}  in the last {days}. Dexter suggests creating lookalikes from your "
                          "most engaged customer base.",
                 breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE, action_breakdown=ActionBreakdownEnum.NONE),
                 time_interval=DaysEnum.THREE_MONTHS,
                 connective=LogicOperatorEnum.AND,
                 antecedents=[
                     Antecedent(aid=1,
                                atype=AntecedentTypeEnum.VALUE,
                                metric=AvailableMetricEnum.OBJECTIVE.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=ObjectiveEnum.LEAD_GENERATION.value),
                     Antecedent(aid=2,
                                atype=AntecedentTypeEnum.FUZZY_TREND,
                                metric=AvailableMetricEnum.COST_PER_RESULT.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=LinguisticVariableEnum.DECREASING)
                 ]),
        RuleBase(rtype=RuleTypeEnum.CREATIVE,
                 channel=ChannelEnum.FACEBOOK,
                 category=RuleCategoryEnum.IMPROVE_CTR,
                 importance=RuleImportanceEnum.MEDIUM,
                 source=RuleSourceEnum.DEXTER,
                 level=LevelEnum.CAMPAIGN,
                 action=ActionEnum.NONE,
                 template="We've noticed your CTR decreasing over {days} which is a sign of ad fatigue. Dexter suggests launching new ad creatives to help "
                          "with this. Adding new creatives will give a boost to an existing campaign.",
                 breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE, action_breakdown=ActionBreakdownEnum.NONE),
                 time_interval=DaysEnum.THREE_MONTHS,
                 connective=LogicOperatorEnum.AND,
                 antecedents=[
                     Antecedent(aid=1,
                                atype=AntecedentTypeEnum.VALUE,
                                metric=AvailableMetricEnum.OBJECTIVE.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=ObjectiveEnum.LEAD_GENERATION.value),
                     Antecedent(aid=2,
                                atype=AntecedentTypeEnum.FUZZY_TREND,
                                metric=AvailableMetricEnum.CTR.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=LinguisticVariableEnum.DECREASING)
                 ]),
        RuleBase(rtype=RuleTypeEnum.CREATIVE,
                 channel=ChannelEnum.FACEBOOK,
                 category=RuleCategoryEnum.IMPROVE_CONVERSION_RATE,
                 importance=RuleImportanceEnum.LOW,
                 source=RuleSourceEnum.DEXTER,
                 level=LevelEnum.CAMPAIGN,
                 action=ActionEnum.NONE,
                 template="Dexter doesn’t like CR rates dropping by {conversion_rate_difference}. Usually CR drops are from "
                          "ad fatigue, or it can be bad targeting. Refresh your ad creatives as a first step to give them a boost.",
                 breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE, action_breakdown=ActionBreakdownEnum.NONE),
                 time_interval=DaysEnum.THREE_MONTHS,
                 connective=LogicOperatorEnum.AND,
                 antecedents=[
                     Antecedent(aid=1,
                                atype=AntecedentTypeEnum.VALUE,
                                metric=AvailableMetricEnum.OBJECTIVE.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=ObjectiveEnum.LEAD_GENERATION.value),
                     Antecedent(aid=2,
                                atype=AntecedentTypeEnum.FUZZY_TREND,
                                metric=AvailableMetricEnum.CONVERSION_RATE.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=LinguisticVariableEnum.DECREASING)
                 ]),

        # Link clicks
        RuleBase(rtype=RuleTypeEnum.AUDIENCE,
                 channel=ChannelEnum.FACEBOOK,
                 category=RuleCategoryEnum.IMPROVE_CPC,
                 importance=RuleImportanceEnum.HIGH,
                 source=RuleSourceEnum.DEXTER,
                 level=LevelEnum.ADSET,
                 action=ActionEnum.NONE,
                 template="Dexter noticed your CPC has increased by {cpc_difference} over the last {days}. Consider launching these new interests {interests} "
                          "to help grow your reach and find new users that'll convert at a lower cost.",
                 breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE, action_breakdown=ActionBreakdownEnum.NONE),
                 time_interval=DaysEnum.THREE_MONTHS,
                 connective=LogicOperatorEnum.AND,
                 antecedents=[
                     Antecedent(aid=1,
                                atype=AntecedentTypeEnum.VALUE,
                                metric=AvailableMetricEnum.OBJECTIVE.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=ObjectiveEnum.LINK_CLICKS.value),
                     Antecedent(aid=2,
                                atype=AntecedentTypeEnum.FUZZY_TREND,
                                metric=AvailableMetricEnum.CPC.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=LinguisticVariableEnum.INCREASING)
                 ]),
        RuleBase(rtype=RuleTypeEnum.CREATIVE,
                 channel=ChannelEnum.FACEBOOK,
                 category=RuleCategoryEnum.IMPROVE_CPC,
                 importance=RuleImportanceEnum.HIGH,
                 source=RuleSourceEnum.DEXTER,
                 level=LevelEnum.CAMPAIGN,
                 action=ActionEnum.NONE,
                 template="Dexter noticed your link clicks have fallen {link_clicks_difference} over the last {days}. Have you considered testing different "
                          "variations of ad copy or creative?",
                 breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE, action_breakdown=ActionBreakdownEnum.NONE),
                 time_interval=DaysEnum.THREE_MONTHS,
                 connective=LogicOperatorEnum.AND,
                 antecedents=[
                     Antecedent(aid=1,
                                atype=AntecedentTypeEnum.VALUE,
                                metric=AvailableMetricEnum.OBJECTIVE.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=ObjectiveEnum.LINK_CLICKS.value),
                     Antecedent(aid=2,
                                atype=AntecedentTypeEnum.FUZZY_TREND,
                                metric=AvailableMetricEnum.LINK_CLICKS.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=LinguisticVariableEnum.DECREASING)
                 ]),
        RuleBase(rtype=RuleTypeEnum.PERFORMANCE,
                 channel=ChannelEnum.FACEBOOK,
                 category=RuleCategoryEnum.IMPROVE_CPR,
                 importance=RuleImportanceEnum.MEDIUM,
                 source=RuleSourceEnum.DEXTER,
                 level=LevelEnum.CAMPAIGN,
                 action=ActionEnum.NONE,
                 template="Dexter has identified that your cost per result has increased over the last {days}. Have you tried creating a lookalikes "
                          "campaign on messenger to bring your cost down even more?",
                 breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE, action_breakdown=ActionBreakdownEnum.NONE),
                 time_interval=DaysEnum.THREE_MONTHS,
                 connective=LogicOperatorEnum.AND,
                 antecedents=[
                     Antecedent(aid=1,
                                atype=AntecedentTypeEnum.VALUE,
                                metric=AvailableMetricEnum.OBJECTIVE.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=ObjectiveEnum.LINK_CLICKS.value),
                     Antecedent(aid=2,
                                atype=AntecedentTypeEnum.FUZZY_TREND,
                                metric=AvailableMetricEnum.COST_PER_RESULT.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=LinguisticVariableEnum.INCREASING)
                 ]),

        # Messenger
        RuleBase(rtype=RuleTypeEnum.AUDIENCE,
                 channel=ChannelEnum.FACEBOOK,
                 category=RuleCategoryEnum.IMPROVE_CPR,
                 importance=RuleImportanceEnum.HIGH,
                 source=RuleSourceEnum.DEXTER,
                 level=LevelEnum.ADSET,
                 action=ActionEnum.NONE,
                 template="Dexter has identified that your cost per result has increased over the last {days}. Have you tried adding new interests to "
                          "target? Do so now by adding {interests}.",
                 breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE, action_breakdown=ActionBreakdownEnum.NONE),
                 time_interval=DaysEnum.THREE_MONTHS,
                 connective=LogicOperatorEnum.AND,
                 antecedents=[
                     Antecedent(aid=1,
                                atype=AntecedentTypeEnum.VALUE,
                                metric=AvailableMetricEnum.OBJECTIVE.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=ObjectiveEnum.MESSENGER.value),
                     Antecedent(aid=2,
                                atype=AntecedentTypeEnum.FUZZY_TREND,
                                metric=AvailableMetricEnum.COST_PER_RESULT.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=LinguisticVariableEnum.INCREASING)
                 ]),
        RuleBase(rtype=RuleTypeEnum.CREATIVE,
                 channel=ChannelEnum.FACEBOOK,
                 category=RuleCategoryEnum.IMPROVE_CPR,
                 importance=RuleImportanceEnum.MEDIUM,
                 source=RuleSourceEnum.DEXTER,
                 level=LevelEnum.CAMPAIGN,
                 action=ActionEnum.NONE,
                 template="Dexter loves good results. However, we’ve seen your results decrease over the last {days}. Have you considered launching new "
                          "ad copy or creatives to boost your results?",
                 breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE, action_breakdown=ActionBreakdownEnum.NONE),
                 time_interval=DaysEnum.THREE_MONTHS,
                 connective=LogicOperatorEnum.AND,
                 antecedents=[
                     Antecedent(aid=1,
                                atype=AntecedentTypeEnum.VALUE,
                                metric=AvailableMetricEnum.OBJECTIVE.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=ObjectiveEnum.MESSENGER.value),
                     Antecedent(aid=2,
                                atype=AntecedentTypeEnum.FUZZY_TREND,
                                metric=AvailableMetricEnum.RESULTS.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=LinguisticVariableEnum.DECREASING)
                 ]),
        RuleBase(rtype=RuleTypeEnum.AUDIENCE,
                 channel=ChannelEnum.FACEBOOK,
                 category=RuleCategoryEnum.OPTIMIZE_TARGETING,
                 importance=RuleImportanceEnum.MEDIUM,
                 source=RuleSourceEnum.DEXTER,
                 level=LevelEnum.ADSET,
                 action=ActionEnum.NONE,
                 template="Your messenger ads aren't reaching a enough people. Dexter suggests these interests {interests} to find new "
                          "prospects you wouldn’t have normally found otherwise!",
                 breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE, action_breakdown=ActionBreakdownEnum.NONE),
                 time_interval=DaysEnum.THREE_MONTHS,
                 connective=LogicOperatorEnum.AND,
                 antecedents=[
                     Antecedent(aid=1,
                                atype=AntecedentTypeEnum.VALUE,
                                metric=AvailableMetricEnum.OBJECTIVE.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=ObjectiveEnum.MESSENGER.value),
                     Antecedent(aid=2,
                                atype=AntecedentTypeEnum.FUZZY_TREND,
                                metric=AvailableMetricEnum.REACH.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=LinguisticVariableEnum.DECREASING)
                 ]),

        #  Page likes
        RuleBase(rtype=RuleTypeEnum.AUDIENCE,
                 channel=ChannelEnum.FACEBOOK,
                 category=RuleCategoryEnum.IMPROVE_CPR,
                 importance=RuleImportanceEnum.HIGH,
                 source=RuleSourceEnum.DEXTER,
                 level=LevelEnum.ADSET,
                 action=ActionEnum.NONE,
                 template="Dexter has identified that your cost per like has decreased over the last {days}. We suggest you create a new adset and "
                          "consider targeting {interests} to get more likes to your page. ",
                 breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE, action_breakdown=ActionBreakdownEnum.NONE),
                 time_interval=DaysEnum.THREE_MONTHS,
                 connective=LogicOperatorEnum.AND,
                 antecedents=[
                     Antecedent(aid=1,
                                atype=AntecedentTypeEnum.VALUE,
                                metric=AvailableMetricEnum.OBJECTIVE.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=ObjectiveEnum.PAGE_LIKES.value),
                     Antecedent(aid=2,
                                atype=AntecedentTypeEnum.FUZZY_TREND,
                                metric=AvailableMetricEnum.COST_PER_RESULT.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=LinguisticVariableEnum.DECREASING)
                 ]),
        RuleBase(rtype=RuleTypeEnum.AUDIENCE,
                 channel=ChannelEnum.FACEBOOK,
                 category=RuleCategoryEnum.IMPROVE_CPR,
                 importance=RuleImportanceEnum.HIGH,
                 source=RuleSourceEnum.DEXTER,
                 level=LevelEnum.ADSET,
                 action=ActionEnum.NONE,
                 template="Your page likes have decreased by {page_likes_decrease} over the last {days}. Have you considered targeting these interests"
                          " {interests}?",
                 breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE, action_breakdown=ActionBreakdownEnum.NONE),
                 time_interval=DaysEnum.THREE_MONTHS,
                 connective=LogicOperatorEnum.AND,
                 antecedents=[
                     Antecedent(aid=1,
                                atype=AntecedentTypeEnum.VALUE,
                                metric=AvailableMetricEnum.OBJECTIVE.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=ObjectiveEnum.PAGE_LIKES.value),
                     Antecedent(aid=2,
                                atype=AntecedentTypeEnum.FUZZY_TREND,
                                metric=AvailableMetricEnum.PAGE_LIKES.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=LinguisticVariableEnum.DECREASING)
                 ]),

        # Post engagement
        RuleBase(rtype=RuleTypeEnum.CREATIVE,
                 channel=ChannelEnum.FACEBOOK,
                 category=RuleCategoryEnum.IMPROVE_ENGAGEMENT,
                 importance=RuleImportanceEnum.HIGH,
                 source=RuleSourceEnum.DEXTER,
                 level=LevelEnum.CAMPAIGN,
                 action=ActionEnum.NONE,
                 template="Did you know you can drastically improve your post engagement by asking a question in the first sentence of your ad? Dexter "
                          "suggests you make this change to help improve your results!",
                 breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE, action_breakdown=ActionBreakdownEnum.NONE),
                 time_interval=DaysEnum.THREE_MONTHS,
                 connective=LogicOperatorEnum.AND,
                 antecedents=[
                     Antecedent(aid=1,
                                atype=AntecedentTypeEnum.VALUE,
                                metric=AvailableMetricEnum.OBJECTIVE.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=ObjectiveEnum.POST_ENGAGEMENT.value),
                     Antecedent(aid=2,
                                atype=AntecedentTypeEnum.FUZZY_TREND,
                                metric=AvailableMetricEnum.RESULTS.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=LinguisticVariableEnum.DECREASING)
                 ]),
        RuleBase(rtype=RuleTypeEnum.CREATIVE,
                 channel=ChannelEnum.FACEBOOK,
                 category=RuleCategoryEnum.IMPROVE_ENGAGEMENT,
                 importance=RuleImportanceEnum.HIGH,
                 source=RuleSourceEnum.DEXTER,
                 level=LevelEnum.CAMPAIGN,
                 action=ActionEnum.NONE,
                 template="Did you know that your cost per result will decrease as you get more post engagement on your ad? Try asking a question, "
                          "keeping in mind who your audience is, to further engage your audience!",
                 breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE, action_breakdown=ActionBreakdownEnum.NONE),
                 time_interval=DaysEnum.THREE_MONTHS,
                 connective=LogicOperatorEnum.AND,
                 antecedents=[
                     Antecedent(aid=1,
                                atype=AntecedentTypeEnum.VALUE,
                                metric=AvailableMetricEnum.OBJECTIVE.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=ObjectiveEnum.POST_ENGAGEMENT.value),
                     Antecedent(aid=2,
                                atype=AntecedentTypeEnum.FUZZY_TREND,
                                metric=AvailableMetricEnum.COST_PER_RESULT.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=LinguisticVariableEnum.DECREASING)
                 ]),
        RuleBase(rtype=RuleTypeEnum.AUDIENCE,
                 channel=ChannelEnum.FACEBOOK,
                 category=RuleCategoryEnum.OPTIMIZE_TARGETING,
                 importance=RuleImportanceEnum.MEDIUM,
                 source=RuleSourceEnum.DEXTER,
                 level=LevelEnum.ADSET,
                 action=ActionEnum.NONE,
                 template="The bigger the audience the more impressions. This also means the more likely it is for your ad to be seen and engaged with. "
                          "Dexter recommends you target these {interests} to reach more people. ",
                 breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE, action_breakdown=ActionBreakdownEnum.NONE),
                 time_interval=DaysEnum.THREE_MONTHS,
                 connective=LogicOperatorEnum.AND,
                 antecedents=[
                     Antecedent(aid=1,
                                atype=AntecedentTypeEnum.VALUE,
                                metric=AvailableMetricEnum.OBJECTIVE.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=ObjectiveEnum.POST_ENGAGEMENT.value),
                     Antecedent(aid=2,
                                atype=AntecedentTypeEnum.FUZZY_TREND,
                                metric=AvailableMetricEnum.IMPRESSIONS.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=LinguisticVariableEnum.DECREASING)
                 ]),

        # Catalog sales
        RuleBase(rtype=RuleTypeEnum.AUDIENCE,
                 channel=ChannelEnum.FACEBOOK,
                 category=RuleCategoryEnum.IMPROVE_ROAS,
                 importance=RuleImportanceEnum.HIGH,
                 source=RuleSourceEnum.DEXTER,
                 level=LevelEnum.ADSET,
                 action=ActionEnum.NONE,
                 template="Dexter has noticed your purchases have slown down by {purchase_decrease_percentage} over the last {days}. Try targeting these "
                          "interests {interests} to increase your sales!",
                 breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE, action_breakdown=ActionBreakdownEnum.NONE),
                 time_interval=DaysEnum.THREE_MONTHS,
                 connective=LogicOperatorEnum.AND,
                 antecedents=[
                     Antecedent(aid=1,
                                atype=AntecedentTypeEnum.VALUE,
                                metric=AvailableMetricEnum.OBJECTIVE.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=ObjectiveEnum.CATALOG_SALES.value),
                     Antecedent(aid=2,
                                atype=AntecedentTypeEnum.FUZZY_TREND,
                                metric=AvailableMetricEnum.PURCHASES.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=LinguisticVariableEnum.DECREASING)
                 ]),
        RuleBase(rtype=RuleTypeEnum.PERFORMANCE,
                 channel=ChannelEnum.FACEBOOK,
                 category=RuleCategoryEnum.IMPROVE_ROAS,
                 importance=RuleImportanceEnum.HIGH,
                 source=RuleSourceEnum.DEXTER,
                 level=LevelEnum.CAMPAIGN,
                 action=ActionEnum.NONE,
                 template="Did you know that you can bring your cost per purchase down significantly by running retargeting campaigns? "
                          "Start this process now to see better results!",
                 breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE, action_breakdown=ActionBreakdownEnum.NONE),
                 time_interval=DaysEnum.THREE_MONTHS,
                 connective=LogicOperatorEnum.AND,
                 antecedents=[
                     Antecedent(aid=1,
                                atype=AntecedentTypeEnum.VALUE,
                                metric=AvailableMetricEnum.OBJECTIVE.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=ObjectiveEnum.CATALOG_SALES.value),
                     Antecedent(aid=2,
                                atype=AntecedentTypeEnum.FUZZY_TREND,
                                metric=AvailableMetricEnum.COST_PER_PURCHASE.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=LinguisticVariableEnum.INCREASING)
                 ]),
        RuleBase(rtype=RuleTypeEnum.AUDIENCE,
                 channel=ChannelEnum.FACEBOOK,
                 category=RuleCategoryEnum.IMPROVE_ROAS,
                 importance=RuleImportanceEnum.MEDIUM,
                 source=RuleSourceEnum.DEXTER,
                 level=LevelEnum.CAMPAIGN,
                 action=ActionEnum.NONE,
                 template="Your ROAS has decreased {roas_decrease} in the last {days} days. Have you optimized for the best age and gender, or looked at your "
                          "best performing placement to make sure your ad is set up for maximum success? ",
                 breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE, action_breakdown=ActionBreakdownEnum.NONE),
                 time_interval=DaysEnum.THREE_MONTHS,
                 connective=LogicOperatorEnum.AND,
                 antecedents=[
                     Antecedent(aid=1,
                                atype=AntecedentTypeEnum.VALUE,
                                metric=AvailableMetricEnum.OBJECTIVE.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=ObjectiveEnum.CATALOG_SALES.value),
                     Antecedent(aid=2,
                                atype=AntecedentTypeEnum.FUZZY_TREND,
                                metric=AvailableMetricEnum.ROAS.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=LinguisticVariableEnum.DECREASING)
                 ]),

        # Reach
        RuleBase(rtype=RuleTypeEnum.AUDIENCE,
                 channel=ChannelEnum.FACEBOOK,
                 category=RuleCategoryEnum.IMPROVE_CPR,
                 importance=RuleImportanceEnum.HIGH,
                 source=RuleSourceEnum.DEXTER,
                 level=LevelEnum.CAMPAIGN,
                 action=ActionEnum.NONE,
                 template="Your reach has decreased, but why? Your relevancy score is below most likely very low, at this point your ads are being penalized "
                          "and delivery is being affected. Dexter suggests creating new ads with new targeting.",
                 breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE, action_breakdown=ActionBreakdownEnum.NONE),
                 time_interval=DaysEnum.THREE_MONTHS,
                 connective=LogicOperatorEnum.AND,
                 antecedents=[
                     Antecedent(aid=1,
                                atype=AntecedentTypeEnum.VALUE,
                                metric=AvailableMetricEnum.OBJECTIVE.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=ObjectiveEnum.REACH.value),
                     Antecedent(aid=2,
                                atype=AntecedentTypeEnum.FUZZY_TREND,
                                metric=AvailableMetricEnum.REACH.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=LinguisticVariableEnum.DECREASING)
                 ]),
        RuleBase(rtype=RuleTypeEnum.AUDIENCE,
                 channel=ChannelEnum.FACEBOOK,
                 category=RuleCategoryEnum.IMPROVE_CPR,
                 importance=RuleImportanceEnum.HIGH,
                 source=RuleSourceEnum.DEXTER,
                 level=LevelEnum.ADSET,
                 action=ActionEnum.NONE,
                 template="Your frequency is fairly high {frequency_value} compared to our industry benchmarks. Have you considered these audiences "
                          "{interests}? Let's test them now, and we'll find the best performing ad for you!",
                 breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE, action_breakdown=ActionBreakdownEnum.NONE),
                 time_interval=DaysEnum.THREE_MONTHS,
                 connective=LogicOperatorEnum.AND,
                 antecedents=[
                     Antecedent(aid=1,
                                atype=AntecedentTypeEnum.VALUE,
                                metric=AvailableMetricEnum.OBJECTIVE.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=ObjectiveEnum.REACH.value),
                     Antecedent(aid=2,
                                atype=AntecedentTypeEnum.FUZZY_VALUE,
                                metric=AvailableMetricEnum.FREQUENCY.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=LinguisticVariableEnum.HIGH)
                 ]),
        RuleBase(rtype=RuleTypeEnum.PERFORMANCE,
                 channel=ChannelEnum.FACEBOOK,
                 category=RuleCategoryEnum.IMPROVE_CPR,
                 importance=RuleImportanceEnum.MEDIUM,
                 source=RuleSourceEnum.DEXTER,
                 level=LevelEnum.CAMPAIGN,
                 action=ActionEnum.NONE,
                 template="Your CPM has increased by {cpm_difference}. It’s one of two reasons: Your frequency is high or your ad isn’t resonating with your "
                          "target audience. Take a look and make the right adjustments!",
                 breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE, action_breakdown=ActionBreakdownEnum.NONE),
                 time_interval=DaysEnum.THREE_MONTHS,
                 connective=LogicOperatorEnum.AND,
                 antecedents=[
                     Antecedent(aid=1,
                                atype=AntecedentTypeEnum.VALUE,
                                metric=AvailableMetricEnum.OBJECTIVE.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=ObjectiveEnum.REACH.value),
                     Antecedent(aid=2,
                                atype=AntecedentTypeEnum.FUZZY_VALUE,
                                metric=AvailableMetricEnum.CPM.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=LinguisticVariableEnum.HIGH)
                 ]),
        #  Video views
        RuleBase(rtype=RuleTypeEnum.PERFORMANCE,
                 channel=ChannelEnum.FACEBOOK,
                 category=RuleCategoryEnum.IMPROVE_ENGAGEMENT,
                 importance=RuleImportanceEnum.HIGH,
                 source=RuleSourceEnum.DEXTER,
                 level=LevelEnum.CAMPAIGN,
                 action=ActionEnum.NONE,
                 template="Your cost per play has gone up {cost_per_play_difference} over the last {days}. Have you optimised your delivery by age "
                          "and gender or for the best performing placement?",
                 breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE, action_breakdown=ActionBreakdownEnum.NONE),
                 time_interval=DaysEnum.THREE_MONTHS,
                 connective=LogicOperatorEnum.AND,
                 antecedents=[
                     Antecedent(aid=1,
                                atype=AntecedentTypeEnum.VALUE,
                                metric=AvailableMetricEnum.OBJECTIVE.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=ObjectiveEnum.VIDEO_VIEWS.value),
                     Antecedent(aid=2,
                                atype=AntecedentTypeEnum.FUZZY_TREND,
                                metric=AvailableMetricEnum.COST_PER_THRUPLAY.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=LinguisticVariableEnum.INCREASING)
                 ]),
        RuleBase(rtype=RuleTypeEnum.CREATIVE,
                 channel=ChannelEnum.FACEBOOK,
                 category=RuleCategoryEnum.IMPROVE_ENGAGEMENT,
                 importance=RuleImportanceEnum.HIGH,
                 source=RuleSourceEnum.DEXTER,
                 level=LevelEnum.CAMPAIGN,
                 action=ActionEnum.NONE,
                 template="Your videos are smashing it and your cost per play is really competitive. Have you tried creating more videos for other "
                          "campaigns that you're running?",
                 breakdown_metadata=BreakdownMetadata(breakdown=BreakdownEnum.NONE, action_breakdown=ActionBreakdownEnum.NONE),
                 time_interval=DaysEnum.THREE_MONTHS,
                 connective=LogicOperatorEnum.AND,
                 antecedents=[
                     Antecedent(aid=1,
                                atype=AntecedentTypeEnum.VALUE,
                                metric=AvailableMetricEnum.OBJECTIVE.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=ObjectiveEnum.VIDEO_VIEWS.value),
                     Antecedent(aid=2,
                                atype=AntecedentTypeEnum.FUZZY_TREND,
                                metric=AvailableMetricEnum.COST_PER_THRUPLAY.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=LinguisticVariableEnum.DECREASING),
                     Antecedent(aid=3,
                                atype=AntecedentTypeEnum.FUZZY_TREND,
                                metric=AvailableMetricEnum.VIDEO_PLAYS.value,
                                operator=LogicOperatorEnum.EQUALS,
                                expected_value=LinguisticVariableEnum.INCREASING)
                 ]),
    ]

    def get_rules_by_action_and_metric(self,
                                       action: ActionEnum = None,
                                       metric: typing.AnyStr = None) -> typing.List[RuleBase]:
        rules = getattr(self, action.value)
        available_rules = [rule for rule in rules if metric in self.__get_rule_metrics_metadata(rule)]
        return available_rules

    def get_rules_by_action(self, action: ActionEnum = None) -> typing.List[RuleBase]:
        available_rules = getattr(self, action.value)
        return available_rules

    @staticmethod
    def __get_rule_metrics_metadata(rule):
        return [metric_metadata.name for metric_metadata in rule.metrics]
