class ProductsData:
    @staticmethod
    def column_header():
        return [
            {"colId": "name", "field": "name", "headerName": "Name", "pinned": "left", "sortable": True},
            {"colId": "variant", "field": "variant", "headerName": "Variants", "sortable": True},
            {
                "colId": "inventory",
                "field": "inventory",
                "headerName": "Inventory",
            },
            {"colId": "brand", "field": "brand", "headerName": "Brand"},
            {
                "colId": "type",
                "field": "type",
                "headerName": "Type",
            },
            {"colId": "tags", "field": "tags", "headerName": "Tags"},
            {"colId": "creative_template", "field": "creative_template", "headerName": "Creative Template"},
            {"colId": "ID", "field": "ID", "headerName": "ID"},
        ]

    @staticmethod
    def set_main_data():
        return [
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here0"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD440",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here1"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD441",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here2"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD442",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here3"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD443",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here4"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD444",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here5"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD445",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here6"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD446",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here7"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD447",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here8"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD448",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here9"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD449",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here10"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4410",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here11"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4411",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here12"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4412",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here13"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4413",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here14"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4414",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here15"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4415",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here16"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4416",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here17"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4417",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here18"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4418",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here19"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4419",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here20"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4420",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here21"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4421",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here22"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4422",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here23"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4423",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here24"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4424",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here25"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4425",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here26"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4426",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here27"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4427",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here28"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4428",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here29"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4429",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here30"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4430",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here31"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4431",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here32"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4432",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here33"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4433",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here34"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4434",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here35"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4435",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here36"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4436",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here37"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4437",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here38"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4438",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here39"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4439",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Testname to go here40"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4440",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here41"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4441",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here42"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4442",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here43"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4443",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here44"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4444",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here45"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4445",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here46"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales20%",
                "ID": "55666DD4446",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here47"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4447",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here48"},
                "variant": 6,
                "inventory": "15 in stock/3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4448",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to gohere49"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4449",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here50"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4450",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here51"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4451",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here52"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4452",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here53"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4453",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here54"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4454",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here55"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4455",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here56"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4456",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here57"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4457",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here58"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4458",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here59"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4459",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here60"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4460",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here61"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4461",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here62"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4462",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here63"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4463",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here64"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4464",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here65"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4465",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here66"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4466",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here67"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4467",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here68"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4468",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here69"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4469",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here70"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4470",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here71"},
                "variant": 6,
                "inventory": "15 in stock/ 3variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4471",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here72"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4472",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here73"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4473",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here74"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "CreativeTemplate": "Sales 20%",
                "ID": "55666DD4474",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here75"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4475",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here76"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4476",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here77"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4477",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here78"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4478",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here79"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4479",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here80"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4480",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here81"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4481",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here82"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4482",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here83"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4483",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here84"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4484",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here85"},
                "variant": 6,
                "inventory": "15 instock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4485",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here86"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4486",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here87"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4487",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here88"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4488",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here89"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4489",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here90"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4490",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here91"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4491",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here92"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4492",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here93"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4493",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here94"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4494",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here95"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4495",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here96"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4496",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here97"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4497",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here98"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4498",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here99"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD4499",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here100"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD44100",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here101"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD44101",
            },
            {
                "status": True,
                "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here102"},
                "variant": 6,
                "inventory": "15 in stock/ 3 variant",
                "brand": "Nike",
                "type": "Accessories",
                "tags": "Hello Tags",
                "creative_template": "Sales 20%",
                "ID": "55666DD44102",
            },
        ]
