class SetsData:
    @staticmethod
    def column_header():
        return [
            {
                "colId": "status",
                "field": "status",
                "headerName": "Status",
                "pinned": "left",
                "sortable": False,
                "isToggle": True,
            },
            {
                "colId": "set_name",
                "field": "set_name",
                "headerName": "Set Name",
                "isNameClickable": True,
                "pinned": "left",
                "sortable": True,
            },
            {"colId": "no_of_product", "field": "no_of_product", "headerName": "Nr. Of Products", "sortable": True},
            {"colId": "no_of_variables", "field": "no_of_variables", "headerName": "Nr. Of Variable", "sortable": True},
            {"colId": "time_created", "field": "time_created", "headerName": "Time Created", "sortable": True},
            {"colId": "last_updated", "field": "last_updated", "headerName": "Last Updated", "sortable": True},
            {
                "colId": "automatisatons",
                "field": "automatisatons",
                "headerName": "Automatisatons",
                "sortable": True,
                "idDropdown": True,
            },
        ]

    @staticmethod
    def set_main_data():
        return [
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 0",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description", "Remove HTMl from product descriptiongg"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 1",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 2",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 3",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 4",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 5",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 6",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 7",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 8",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 9",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 10",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 11",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 12",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 13",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 14",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 15",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 16",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 17",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 18",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 19",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 20",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 21",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 22",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 23",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 24",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 25",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 26",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 27",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 28",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 29",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 30",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 31",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 32",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 33",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 34",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 35",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 36",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 37",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 38",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 39",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 40",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 41",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 42",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 43",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 44",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 45",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 46",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 47",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 48",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 49",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 50",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 51",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 52",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 53",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 54",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 55",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 56",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 57",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 58",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 59",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 60",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 61",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 62",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 63",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 64",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 65",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 66",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 67",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 68",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 69",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 70",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 71",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 72",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 73",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 74",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 75",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 76",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 77",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 78",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 79",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 80",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 81",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 82",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 83",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 84",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 85",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 86",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 87",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 88",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 89",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 90",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 91",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 92",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 93",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 94",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 95",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 96",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 97",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 98",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 99",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 100",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 101",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 102",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 103",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
            {
                "status": "ACTIVE",
                "set_name": "Test name to go here 104",
                "no_of_product": 6000,
                "no_of_variables": 6000,
                "time_created": "02/02/2020",
                "last_updated": "02/02/2020",
                "automatisatons": ["Remove HTMl from product description"],
            },
        ]
