test = [
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here0"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here1"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here2"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here3"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here4"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here5"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here6"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here7"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here8"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here9"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test nameto go here10"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here11"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here12"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here13"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here14"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here15"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here16"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here17"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here18"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here19"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here20"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here21"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here22"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here23"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here24"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here25"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here26"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here27"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here28"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here29"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here30"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here31"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here32"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here33"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here34"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here35"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here36"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here37"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here38"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here39"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here40"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here41"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here42"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here43"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here44"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here45"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here46"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here47"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here48"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here49"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here50"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here51"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here52"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here53"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here54"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here55"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here56"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here57"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here58"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here59"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here60"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here61"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here62"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here63"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here64"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here65"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here66"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here67"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here68"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here69"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here70"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here71"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here72"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here73"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here74"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here75"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here76"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here77"},
        "attribute_1": "Custom1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here78"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here79"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here80"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here81"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here82"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here83"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here84"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here85"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here86"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here87"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here88"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here89"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here90"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here91"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here92"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here93"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here94"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here95"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here96"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here97"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here98"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here99"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here100"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here101"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
    {
        "status": True,
        "name": {"image": "assets/images/catalog-product/shopify.svg", "name": "Test name to go here102"},
        "attribute_1": "Custom 1",
        "attribute_2": "Custom 2",
        "attribute_3": "Custom 3",
        "inventory": 6,
        "price": 100,
        "compared_price": 200,
        "discount": "505 off",
    },
]
