from enum import Enum


class AdWordsPerformanceReportType(Enum):
    CAMPAIGN = "CAMPAIGN_PERFORMANCE_REPORT"
    AD_GROUP = "ADGROUP_PERFORMANCE_REPORT"
    AD = "AD_PERFORMANCE_REPORT"
    GENDER = "GENDER_PERFORMANCE_REPORT"
    AGE_RANGE = "AGE_RANGE_PERFORMANCE_REPORT"
    GEO = "GEO_PERFORMANCE_REPORT"
    KEYWORDS = "KEYWORDS_PERFORMANCE_REPORT"
