from Core.Tools.Misc.EnumerationBase import EnumerationBase
from PotterFacebookAccounts.Infrastructure.IntegrationEvents.GetAdAccountsAmountSpentInsightMessageRequestHandler import \
    GetAdAccountsAmountSpentInsightMessageRequestHandler
from PotterFacebookAccounts.Infrastructure.IntegrationEvents.GetBusinessOwnersTreesMessageRequestHandler import \
    GetBusinessOwnersTreesMessageRequestHandler


class HandlersEnum(EnumerationBase):
    BUSINESS_OWNER_UPDATE_REQUEST = GetBusinessOwnersTreesMessageRequestHandler
    BUSINESS_OWNER_ACCOUNT_SPEND_REQUEST = GetAdAccountsAmountSpentInsightMessageRequestHandler
