from enum import Enum, auto


# Note: This enum is based on Product Catalog Currencies table.
class CurrencyEnum(Enum):
    USD = auto()
    AED = auto()
    ARS = auto()
    AUD = auto()
    BGN = auto()
    BOB = auto()
    BRL = auto()
    CAD = auto()
    CHF = auto()
    CLP = auto()
    CNY = auto()
    COP = auto()
    CZK = auto()
    DKK = auto()
    EGP = auto()
    EUR = auto()
    FRF = auto()
    GBP = auto()
    HKD = auto()
    HRK = auto()
    HUF = auto()
    IDR = auto()
    ILS = auto()
    INR = auto()
    JPY = auto()
    KRW = auto()
    LTL = auto()
    MAD = auto()
    MXN = auto()
    MYR = auto()
    NOK = auto()
    NZD = auto()
    PEN = auto()
    PHP = auto()
    PKR = auto()
    PLN = auto()
    RON = auto()
    RSD = auto()
    RUB = auto()
    SAR = auto()
    SEK = auto()
    SGD = auto()
    THB = auto()
    TRY = auto()
    TWD = auto()
    UAH = auto()
    VEF = auto()
    VND = auto()
    ZAR = auto()
