# Generated by Django 2.2 on 2019-05-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawInterest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('type', models.CharField(default='', max_length=50)),
                ('path', models.TextField(null=True)),
                ('description', models.TextField(default='', max_length=255)),
                ('audience_size', models.BigIntegerField(blank=True)),
                ('real_time_cluster', models.BooleanField()),
            ],
        ),
    ]
