# Generated by Django 2.2 on 2019-05-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('interest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawinterest',
            name='key',
            field=models.CharField(default='', max_length=50),
        ),
    ]
