# Generated by Django 2.2 on 2019-05-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('interest', '0003_auto_20190528_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawinterest',
            name='real_time_cluster',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
