apiVersion: v1
kind: Service
metadata:
  name: prod-filed-facebook-dexter-api
  labels:
    run: prod-filed-facebook-dexter-api
spec:
  ports:
  - port: 43700
  selector:
    run: prod-filed-facebook-dexter-api