import numpy as np

from Core.Dexter.Infrastructure.Domain.FuzzyEngine.FuzzySets.FuzzyMembershipFunction import LinearMembershipFunction
from Core.Dexter.Infrastructure.Domain.FuzzyEngine.FuzzySets.FuzzySets import LinguisticVariable, Fuzzyfier
from FacebookDexter.Engine.Algorithms.FuzzyRuleBasedSingleMetricOptimization.Metrics.FacebookAvailableSingleMetricEnum import \
    FacebookAvailableSingleMetricEnum
from FacebookDexter.Infrastructure.Domain.FuzzyEngine.FacebookFuzzySets import FacebookLinguisticVariableEnum

INCREASING_LINEAR_PARAMS = {
    "a": 2.0 / np.pi,
    "b": 0.0
}

DECREASING_LINEAR_PARAMS = {
    "a": -2.0 / np.pi,
    "b": 0.0
}

INCREASING_LINEAR_PARAMS_CPM = {
    "a": 16 / (7 * np.pi),
    "b": -(1 / 7)
}

DECREASING_LINEAR_PARAMS_CPM = {
    "a": -16 / (7 * np.pi),
    "b": -(1 / 7)
}

TREND_METRIC_FUZZYFIER_COLLECTION = [
    Fuzzyfier(metric_name=FacebookAvailableSingleMetricEnum.CPC.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=FacebookAvailableSingleMetricEnum.CPM.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=FacebookAvailableSingleMetricEnum.CTR.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=FacebookAvailableSingleMetricEnum.COST_PER_RESULT.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=FacebookAvailableSingleMetricEnum.COST_PER_APP_INSTALL.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=FacebookAvailableSingleMetricEnum.COST_PER_PURCHASE.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=FacebookAvailableSingleMetricEnum.COST_PER_THRUPLAY.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=FacebookAvailableSingleMetricEnum.CR.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=FacebookAvailableSingleMetricEnum.ENGAGEMENT_RATE.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=FacebookAvailableSingleMetricEnum.ROAS.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=FacebookAvailableSingleMetricEnum.RESULTS.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=FacebookAvailableSingleMetricEnum.SPEND.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=FacebookAvailableSingleMetricEnum.REACH.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=FacebookAvailableSingleMetricEnum.LINK_CLICKS.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=FacebookAvailableSingleMetricEnum.PAGE_LIKES.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=FacebookAvailableSingleMetricEnum.IMPRESSIONS.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=FacebookAvailableSingleMetricEnum.PURCHASES.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=FacebookAvailableSingleMetricEnum.VIDEO_PLAYS.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=FacebookAvailableSingleMetricEnum.LEADS.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=FacebookAvailableSingleMetricEnum.RSVPS.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=FacebookAvailableSingleMetricEnum.APP_INSTALLS.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=FacebookAvailableSingleMetricEnum.CONVERSIONS.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=FacebookAvailableSingleMetricEnum.THRUPLAYS.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=FacebookAvailableSingleMetricEnum.UNIQUE_CLICKS.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=FacebookAvailableSingleMetricEnum.POST_LIKES.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=FacebookAvailableSingleMetricEnum.POST_COMMENTS.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=FacebookAvailableSingleMetricEnum.POST_SHARES.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=FacebookAvailableSingleMetricEnum.POST_VIEWS.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=FacebookAvailableSingleMetricEnum.PURCHASES_VALUE.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=FacebookAvailableSingleMetricEnum.CLICKS.value.name,
              linguistic_levels=[LinguisticVariable(FacebookLinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(FacebookLinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))])
]
