import numpy as np

from GoogleDexter.Engine.Algorithms.FuzzyRuleBasedOptimization.Metrics.AvailableMetricEnum import AvailableMetricEnum
from GoogleDexter.Infrastructure.FuzzyEngine.FuzzySets.FuzzyMembershipFunction import LinearMembershipFunction
from GoogleDexter.Infrastructure.FuzzyEngine.FuzzySets.FuzzySets import Fuzzyfier, LinguisticVariable, \
    LinguisticVariableEnum

INCREASING_LINEAR_PARAMS = {
    "a": 2.0 / np.pi,
    "b": 0.0
}

DECREASING_LINEAR_PARAMS = {
    "a": -2.0 / np.pi,
    "b": 0.0
}

TREND_METRIC_FUZZYFIER_COLLECTION = [
    Fuzzyfier(metric_name=AvailableMetricEnum.CPC.value.name,
              linguistic_levels=[LinguisticVariable(LinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(LinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=AvailableMetricEnum.CPM.value.name,
              linguistic_levels=[LinguisticVariable(LinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(LinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=AvailableMetricEnum.CTR.value.name,
              linguistic_levels=[LinguisticVariable(LinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(LinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=AvailableMetricEnum.COST_PER_RESULT.value.name,
              linguistic_levels=[LinguisticVariable(LinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(LinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    # Fuzzyfier(metric_name=AvailableMetricEnum.COST_PER_APP_INSTALL.value.name,
    #           linguistic_levels=[LinguisticVariable(LinguisticVariableEnum.DECREASING,
    #                                                 LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
    #                              LinguisticVariable(LinguisticVariableEnum.INCREASING,
    #                                                 LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=AvailableMetricEnum.COST_PER_PURCHASE.value.name,
              linguistic_levels=[LinguisticVariable(LinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(LinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    # Fuzzyfier(metric_name=AvailableMetricEnum.COST_PER_THRUPLAY.value.name,
    #           linguistic_levels=[LinguisticVariable(LinguisticVariableEnum.DECREASING,
    #                                                 LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
    #                              LinguisticVariable(LinguisticVariableEnum.INCREASING,
    #                                                 LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=AvailableMetricEnum.CR.value.name,
              linguistic_levels=[LinguisticVariable(LinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(LinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    # Fuzzyfier(metric_name=AvailableMetricEnum.ENGAGEMENT_RATE.value.name,
    #           linguistic_levels=[LinguisticVariable(LinguisticVariableEnum.DECREASING,
    #                                                 LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
    #                              LinguisticVariable(LinguisticVariableEnum.INCREASING,
    #                                                 LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=AvailableMetricEnum.ROAS.value.name,
              linguistic_levels=[LinguisticVariable(LinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(LinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=AvailableMetricEnum.RESULTS.value.name,
              linguistic_levels=[LinguisticVariable(LinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(LinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=AvailableMetricEnum.SPEND.value.name,
              linguistic_levels=[LinguisticVariable(LinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(LinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=AvailableMetricEnum.REACH.value.name,
              linguistic_levels=[LinguisticVariable(LinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(LinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=AvailableMetricEnum.LINK_CLICKS.value.name,
              linguistic_levels=[LinguisticVariable(LinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(LinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    # Fuzzyfier(metric_name=AvailableMetricEnum.PAGE_LIKES.value.name,
    #           linguistic_levels=[LinguisticVariable(LinguisticVariableEnum.DECREASING,
    #                                                 LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
    #                              LinguisticVariable(LinguisticVariableEnum.INCREASING,
    #                                                 LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=AvailableMetricEnum.IMPRESSIONS.value.name,
              linguistic_levels=[LinguisticVariable(LinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(LinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=AvailableMetricEnum.PURCHASES.value.name,
              linguistic_levels=[LinguisticVariable(LinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(LinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    # Fuzzyfier(metric_name=AvailableMetricEnum.VIDEO_PLAYS.value.name,
    #           linguistic_levels=[LinguisticVariable(LinguisticVariableEnum.DECREASING,
    #                                                 LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
    #                              LinguisticVariable(LinguisticVariableEnum.INCREASING,
    #                                                 LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=AvailableMetricEnum.LEADS.value.name,
              linguistic_levels=[LinguisticVariable(LinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(LinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    # Fuzzyfier(metric_name=AvailableMetricEnum.RSVPS.value.name,
    #           linguistic_levels=[LinguisticVariable(LinguisticVariableEnum.DECREASING,
    #                                                 LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
    #                              LinguisticVariable(LinguisticVariableEnum.INCREASING,
    #                                                 LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    # Fuzzyfier(metric_name=AvailableMetricEnum.APP_INSTALLS.value.name,
    #           linguistic_levels=[LinguisticVariable(LinguisticVariableEnum.DECREASING,
    #                                                 LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
    #                              LinguisticVariable(LinguisticVariableEnum.INCREASING,
    #                                                 LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=AvailableMetricEnum.CONVERSIONS.value.name,
              linguistic_levels=[LinguisticVariable(LinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(LinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    # Fuzzyfier(metric_name=AvailableMetricEnum.THRUPLAYS.value.name,
    #           linguistic_levels=[LinguisticVariable(LinguisticVariableEnum.DECREASING,
    #                                                 LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
    #                              LinguisticVariable(LinguisticVariableEnum.INCREASING,
    #                                                 LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    # Fuzzyfier(metric_name=AvailableMetricEnum.UNIQUE_CLICKS.value.name,
    #           linguistic_levels=[LinguisticVariable(LinguisticVariableEnum.DECREASING,
    #                                                 LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
    #                              LinguisticVariable(LinguisticVariableEnum.INCREASING,
    #                                                 LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    # Fuzzyfier(metric_name=AvailableMetricEnum.POST_LIKES.value.name,
    #           linguistic_levels=[LinguisticVariable(LinguisticVariableEnum.DECREASING,
    #                                                 LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
    #                              LinguisticVariable(LinguisticVariableEnum.INCREASING,
    #                                                 LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    # Fuzzyfier(metric_name=AvailableMetricEnum.POST_COMMENTS.value.name,
    #           linguistic_levels=[LinguisticVariable(LinguisticVariableEnum.DECREASING,
    #                                                 LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
    #                              LinguisticVariable(LinguisticVariableEnum.INCREASING,
    #                                                 LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    # # Fuzzyfier(metric_name=AvailableMetricEnum.POST_SHARES.value.name,
    #           linguistic_levels=[LinguisticVariable(LinguisticVariableEnum.DECREASING,
    #                                                 LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
    #                              LinguisticVariable(LinguisticVariableEnum.INCREASING,
    #                                                 LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    # Fuzzyfier(metric_name=AvailableMetricEnum.POST_VIEWS.value.name,
    #           linguistic_levels=[LinguisticVariable(LinguisticVariableEnum.DECREASING,
    #                                                 LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
    #                              LinguisticVariable(LinguisticVariableEnum.INCREASING,
    #                                                 LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=AvailableMetricEnum.PURCHASES_VALUE.value.name,
              linguistic_levels=[LinguisticVariable(LinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(LinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))]),
    Fuzzyfier(metric_name=AvailableMetricEnum.CLICKS.value.name,
              linguistic_levels=[LinguisticVariable(LinguisticVariableEnum.DECREASING,
                                                    LinearMembershipFunction(**DECREASING_LINEAR_PARAMS)),
                                 LinguisticVariable(LinguisticVariableEnum.INCREASING,
                                                    LinearMembershipFunction(**INCREASING_LINEAR_PARAMS))])
]
