# todo: check with FB values
from enum import Enum


class GoogleObjectiveEnum(Enum):
    APP_INSTALLS = 'APP_INSTALLS'
    BRAND_AWARENESS = 'BRAND_AWARENESS'
    CONVERSIONS = 'CONVERSIONS'
    EVENT_RESPONSES = 'EVENT_RESPONSES'
    LEAD_GENERATION = 'LEAD_GENERATION'
    LINK_CLICKS = 'LINK_CLICKS'
    MESSAGES = 'MESSAGES'
    PAGE_LIKES = 'PAGE_LIKES'
    POST_ENGAGEMENT = 'POST_ENGAGEMENT'
    PRODUCT_CATALOG_SALES = 'PRODUCT_CATALOG_SALES'
    REACH = 'REACH'
    VIDEO_VIEWS = 'VIDEO_VIEWS'
