apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev2-filed-targeting-search
spec:
  selector:
    matchLabels:
      run: dev2-filed-targeting-search
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1       
      maxUnavailable: 0
  template:
    metadata:
      labels:
        run: dev2-filed-targeting-search
    spec:
      hostAliases:
        - ip: "192.168.1.211"
          hostnames:
          - "dev2.filed.com"
        - ip: "192.168.2.91"
          hostnames:
          - "dev2.mongodb" 
      containers:
        - name: dev2-filed-targeting-search
          image: ct.filed.com/dev2-filed-targeting-search:v0.1
          imagePullPolicy: Always
        ports: 
        - containerPort : 47222
      imagePullSecrets:
        - name: regcred  