apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev2-mongodb-storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 40Gi      