# Facebook Placements
from facebook_business.adobjects.contentdeliveryreport import ContentDeliveryReport
from Potter.FacebookCampaignsBuilder.Api.Catalogs.CatalogNode import CatalogNode

facebook_feed_placement = CatalogNode(ContentDeliveryReport.Position.feed)
facebook_instant_article_placement = CatalogNode(ContentDeliveryReport.Position.instant_article)
facebook_video_feeds_placement = CatalogNode(ContentDeliveryReport.Position.video_feeds)
facebook_right_column_placement = CatalogNode(ContentDeliveryReport.Position.right_hand_column)
facebook_marketplace_placement = CatalogNode(ContentDeliveryReport.Position.marketplace)
facebook_stories_placement = CatalogNode(ContentDeliveryReport.Position.facebook_stories)
facebook_search_results_placement = CatalogNode(ContentDeliveryReport.Position.search)
facebook_in_stream_videos_placement = CatalogNode(ContentDeliveryReport.Position.instream_video)

# Instagram Placements
instagram_feed_placement = CatalogNode(ContentDeliveryReport.Position.feed)
instagram_stories_placement = CatalogNode(ContentDeliveryReport.Position.instagram_stories)
instagram_explore_placement = CatalogNode(ContentDeliveryReport.Position.instagram_explore)

# Audience Network Placements
audience_network_native_placement = CatalogNode(ContentDeliveryReport.Position.an_classic)
audience_network_in_stream_videos_placement = CatalogNode(ContentDeliveryReport.Position.instream_video)
audience_network_rewarded_videos_placement = CatalogNode(ContentDeliveryReport.Position.rewarded_video)

