from Core.Web.FacebookGraphAPI.Models.FieldsMetadata import FieldsMetadata

INSIGHTS_SYNCRONIZER_FIELDS = [
    FieldsMetadata.results,
    FieldsMetadata.amount_spent,
    FieldsMetadata.reach,
    FieldsMetadata.link_clicks,
    FieldsMetadata.page_likes,
    FieldsMetadata.impressions,
    FieldsMetadata.purchases_total,
    FieldsMetadata.video_plays,
    FieldsMetadata.leads_total,
    FieldsMetadata.event_responses,
    FieldsMetadata.website_app_installs_total,
    FieldsMetadata.conversions,
    FieldsMetadata.thru_plays,
    FieldsMetadata.unique_link_clicks,
    # FieldsMetadata.post_likes,
    FieldsMetadata.post_comments,
    FieldsMetadata.post_shares,
    FieldsMetadata.photo_views,
    FieldsMetadata.post_engagement,
    FieldsMetadata.purchases_value,
    FieldsMetadata.clicks_all,
    FieldsMetadata.objective,
    FieldsMetadata.quality_ranking,
    FieldsMetadata.account_id,
    FieldsMetadata.account_name,
    FieldsMetadata.campaign_id,
    FieldsMetadata.campaign_name,
    FieldsMetadata.adset_id,
    FieldsMetadata.adset_name,
    FieldsMetadata.ad_id,
    FieldsMetadata.ad_name,
    FieldsMetadata.date_start,
    FieldsMetadata.date_stop
]
