from Core.Web.FacebookGraphAPI.Models.FieldsMetadata import FieldsMetadata

INSIGHTS_SYNCHRONIZER_FIELDS = [
    FieldsMetadata.results,
    FieldsMetadata.amount_spent,
    FieldsMetadata.reach,
    FieldsMetadata.link_clicks,
    FieldsMetadata.page_likes,
    FieldsMetadata.impressions,
    FieldsMetadata.purchases_total,
    # FieldsMetadata.video_plays,
    FieldsMetadata.leads_total,
    FieldsMetadata.event_responses,
    FieldsMetadata.app_installs_total,
    FieldsMetadata.conversions,
    FieldsMetadata.thru_plays,
    FieldsMetadata.unique_link_clicks,
    # FieldsMetadata.post_likes,
    FieldsMetadata.post_comments,
    FieldsMetadata.post_shares,
    FieldsMetadata.photo_views,
    FieldsMetadata.post_engagement,
    FieldsMetadata.purchases_value,
    FieldsMetadata.clicks_all,
    FieldsMetadata.objective,
    FieldsMetadata.quality_ranking,
    FieldsMetadata.account_id,
    FieldsMetadata.account_name,
    FieldsMetadata.campaign_id,
    FieldsMetadata.campaign_name,
    FieldsMetadata.adset_id,
    FieldsMetadata.adset_name,
    FieldsMetadata.ad_id,
    FieldsMetadata.ad_name,
    FieldsMetadata.date_start,
    FieldsMetadata.date_stop,
    FieldsMetadata.frequency,
    FieldsMetadata.video_plays_3s,
    FieldsMetadata.video_plays_95p,
    FieldsMetadata.video_average_play_time,
    FieldsMetadata.adds_to_cart_total,
    FieldsMetadata.adds_to_cart_value,
    FieldsMetadata.website_checkouts_initiated_value,
    FieldsMetadata.website_checkouts_initiated_total,
    FieldsMetadata.unique_clicks_all,
    FieldsMetadata.unique_ctr_all,
    FieldsMetadata.messaging_conversations_started,
    FieldsMetadata.unique_link_click_through_rate,
    FieldsMetadata.content_views_unique_total,
    FieldsMetadata.adds_to_cart_unique,
    FieldsMetadata.checkouts_initiated_unique_total,
    FieldsMetadata.website_purchases_value,
    FieldsMetadata.photo_views,
    FieldsMetadata.other_offline_conversions_total,
    FieldsMetadata.landing_page_views_total,
]

FREEMIUM_USER_INSIGHTS_SYNCHRONIZER_FIELDS = [
    FieldsMetadata.amount_spent,
    FieldsMetadata.reach,
    FieldsMetadata.link_clicks,
    FieldsMetadata.page_likes,
    FieldsMetadata.impressions,
    FieldsMetadata.purchases_total
]
