from Core.Tools.Misc.EnumerationBase import EnumerationBase
from Potter.FacebookProductCatalogs.Infrastructure.IntegrationEvents.GetProductCatalogsForBusinessRequestHandler import \
    GetProductCatalogsForBusinessRequestHandler
from Potter.FacebookProductCatalogs.Infrastructure.IntegrationEvents.GetProductSetsForCatalogRequestHandler import \
    GetProductSetsForCatalogRequestHandler
from Potter.FacebookProductCatalogs.Infrastructure.IntegrationEvents.GetProductsForCatalogRequestHandler import \
    GetProductsForCatalogRequestHandler


class HandlersEnum(EnumerationBase):
    GET_PRODUCT_CATALOGS_FOR_BUSINESS = GetProductCatalogsForBusinessRequestHandler
    GET_PRODUCT_SETS_FOR_CATALOG = GetProductSetsForCatalogRequestHandler
    GET_PRODUCTS_FOR_CATALOG = GetProductsForCatalogRequestHandler
