apiVersion: v1
kind: Service
metadata:
  name: dev2-filed-potter-facebook-apps-background-tasks
  labels:
    run: dev2-filed-potter-facebook-apps-background-tasks
spec:
  ports:
    - port: 47231
  selector:
    run: dev2-filed-potter-facebook-apps-background-tasks